DERCBOT 324 and 332 : fix - edit faq title and faq search
CreditMutuelArkea/tock pull request #124
Opened 2022-11-04 09:45 UTC by assouktim

2022-11-07 10:22 UTC, djowalker reviewed
Des questions à répondre mais pas vraiment de soucis à remonter

2022-11-07 10:22 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +                    i18nDao.getLabelById(faqQueryResult.i18nId)
L'idée ici était de ne pas refaire un appel de base de données mais d'utiliser les données qui étaient déjà chargées depuis les faq.
C'est pas forcément très lisible j'en conviens.

2022-11-07 10:22 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +                    i18nDao.getLabelById(faqQueryResult.i18nId)
Avec le i18nLabels dit optionnel

2022-11-07 10:22 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +    private fun createOrUpdateFaqIntent(query: FaqDefinitionRequest, application: ApplicationDefinition): IntentDefinition {
En fait il y a une sorte de reprise du code précédent ?
Avec le createOrUpdateIntent de l'adminService ?

2022-11-07 10:22 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +                    i18nDao.getLabelById(faqQueryResult.i18nId)
C'était ça le soucis pour les UNKNOWN ?

2022-11-07 10:22 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> -                    val botAdminService = spyk<BotAdminService>()
ça a été enlevé car ce n'est pas dans le scope des FAQ donc ?

2022-11-07 10:22 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> -                    verify(exactly = 0) {
idem ici ?

2022-11-08 09:50 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +                    i18nDao.getLabelById(faqQueryResult.i18nId)
On ne peux pas utiliser cette liste, car elle contient pas tous les libelles de la bdd, elle contient uniquement ce qui match avec le texte recherché. Si une FAQ remonte car sa description correspond à la recherche, l'answer lui ne l'ai pas forcément. D’où le bug.

2022-11-08 09:52 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +    private fun createOrUpdateFaqIntent(query: FaqDefinitionRequest, application: ApplicationDefinition): IntentDefinition {
Oui, car au début la RG consiste à ne pas MAJ l'intention. Mais plus mtn.

2022-11-08 10:02 UTC, assouktim commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> -                    val botAdminService = spyk<BotAdminService>()
la méthode que tu test est déjà exéctué à la ligne 416, les mock qui viennent après ne serve plus à rien. ce qui prend le relais c'est les verify, et eux n'ont pas besoin des mocks. Donc j'ai retiré le code.

2022-11-08 10:03 UTC, assouktim commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> -                    verify(exactly = 0) {
idem

2022-11-09 16:54 UTC, djowalker requested changes
Renommage et commentaire comme indiqué

2022-11-09 16:54 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +                    i18nDao.getLabelById(faqQueryResult.i18nId)
Dans ce cas pour aller au bout faut virer i18nLabels en paramètres et renommer la méthode et son commentaire en toute cohérence.

2022-11-09 16:54 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +                    i18nDao.getLabelById(faqQueryResult.i18nId)
Et voir pour réussir à tester cette méthode sans la mocker si c'est le cas.
EDIT : m'as t'as l'air de l'avoir géré dans initSearchFaqMockWithLabelsSearch

2022-11-14 09:38 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +                    i18nDao.getLabelById(faqQueryResult.i18nId)
Je pense que ça n'a pas de sens de faire un appel direct, on est sur un service coté admin server, c'est normal que je mock l'appel bdd.

2022-11-14 16:47 UTC, merged