Feature/faq/dercbot 331
CreditMutuelArkea/tock pull request #126
Opened 2022-11-09 08:56 UTC by henriSedjame

DERCBOT-331

[backend] 
- replace FaqDefinition's  applicationId attribute by botId

[frontend]
- replace FadDefinition's applicationId attribute by applicationName

2022-11-09 09:08 UTC, rkuffer requested changes
Le package-lock.json doit être sorti de ce commit. 
D'une part il n'a pas de raisons d'être commité puisqu'aucune modification n'a été apportée à package.json mais surtout toutes les url ont été remplacées par le l'url de registry Arkea qui ne sera pas accessible à d'autres utilisateurs de Tock. 
De façon général, si le dev en question n'a pas apporté de modification au package.json, le package-lock doit être "discardé".

2022-11-09 09:49 UTC, djowalker requested changes
Des petites questions.
Et pour les commentaires des anciennes fonctions tu aurais pu les enlever directement, on voit ça bien avec les diff git.

2022-11-09 09:49 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> +            "",
Certes on est en mock mais pourquoi mettre une chaîne vide ?

2022-11-09 09:49 UTC, djowalker commented on bot/admin/web/src/app/faq/faq-management/faq-management-edit/faq-management-edit.component.spec.ts
> +  applicationName: '1',
Certes on est toujours en mock mais plutôt mettre une chaîne de caractères : exemple "appName" ou "botId" non ?

2022-11-09 09:49 UTC, djowalker commented on bot/admin/web/src/app/faq/faq-management/faq-management-list/faq-management-list.component.spec.ts
> +    applicationName: '1',
idem chaîne de caractères?

2022-11-09 09:49 UTC, djowalker commented on nlp/front/service/src/main/kotlin/ApplicationConfigurationService.kt
> +            = getApplicationById(id)?.let { faqDefinitionDAO.getFaqDefinitionByBotId(it.name) } ?: arrayListOf()
le into(ArrayList) dans la méthode ne gère pas déjà le cas où c'est vide ? Bon peut-être pas le null cependant mais on est sur des objets non nullables normalement.

2022-11-09 09:49 UTC, djowalker commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +import org.litote.kmongo.*
Côté SNCF ils sont un peu chiant pour les import *.
Voir côté conf IntelliJ pour avoir les imports explicites

2022-11-09 09:59 UTC, henriSedjame commented on nlp/front/service/src/main/kotlin/ApplicationConfigurationService.kt
> +            = getApplicationById(id)?.let { faqDefinitionDAO.getFaqDefinitionByBotId(it.name) } ?: arrayListOf()
L'appel du let sur un Nullable renvoie un nullable, il faut donc le gérer

2022-11-09 10:00 UTC, henriSedjame commented on bot/admin/web/src/app/faq/faq-management/faq-management-list/faq-management-list.component.spec.ts
> +    applicationName: '1',
Je change ça :)

2022-11-09 10:05 UTC, henriSedjame commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +import org.litote.kmongo.*
Ah oui, aps fait exprès celui là, IntelliJ a ses caprices :)

2022-11-09 10:25 UTC, djowalker commented on nlp/front/service/src/main/kotlin/ApplicationConfigurationService.kt
> +            = getApplicationById(id)?.let { faqDefinitionDAO.getFaqDefinitionByBotId(it.name) } ?: arrayListOf()
En effet

2022-11-14 13:14 UTC, brandonsechet approved these changes

2022-11-14 13:18 UTC, rkuffer approved these changes

2022-11-14 15:50 UTC, djowalker reviewed
Des petits changements de commentaires, sinon RAS

2022-11-15 09:25 UTC, henriSedjame commented on bot/admin/server/src/test/kotlin/BotMediaMessageSerializationTest.kt
> -            "{\"actions\":[{\"title\":{\"_id\":\"id\",\"namespace\":\"namespace\",\"category\":\"category\",\"i18n\":[],\"defaultLabel\":null,\"defaultLocale\":\"en\",\"version\":0},\"url\":\"https:/
Oui il y a un probleme, le test ne passe pas et pour cause: lors de la sérialisation les propriétés nulles sont ignorées par défaut

2022-11-15 09:26 UTC, henriSedjame commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> +        private val faqDefinition = FaqDefinition(faqId, "", intentId, i18nId, tagList, true, now, now)
Oups c'est un oubli ça.

2022-11-15 09:26 UTC, henriSedjame commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +     * @param botId : the applicationId
En effet, je corrige ça

2022-11-18 15:08 UTC, djowalker commented on bot/admin/server/src/main/kotlin/constants/Properties.kt
> +    const val FAQ_MIGRATION_ENABLED = "faq_migration_enabled"
Très bien le fichier le propriété.
Sur l'ensemble de l'appli, il préfixes beaucoup de variable en `tock_` qu'en penses-tu ?

2022-11-18 15:11 UTC, djowalker commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +    override fun getTags(botId: String): List<String> {
Bizarre que cette méthode apparaisse en tant que nouvelle méthode ?

2022-11-18 15:17 UTC, djowalker commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +        data class FaqProjection(
Petit commentaire pour indiquer que c'est la représentation de l'ancienne version.

2022-11-18 16:10 UTC, djowalker commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +    override fun makeMigration(botIdSupplier: (Id<ApplicationDefinition>) -> String?) {
Je sais qu'on est au stade du ponctuel mais ça serait pas mieux de décaler le code dans un.e autre fichier/classe concernant la migration ?

2022-11-18 16:11 UTC, djowalker reviewed
Des questions et du commentaire mais pas grand chose à signaler.

2022-11-21 07:55 UTC, henriSedjame commented on bot/admin/server/src/main/kotlin/constants/Properties.kt
> +    const val FAQ_MIGRATION_ENABLED = "faq_migration_enabled"
Si c'est la règle il faut la respecter :)

2022-11-21 07:56 UTC, henriSedjame commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +    override fun makeMigration(botIdSupplier: (Id<ApplicationDefinition>) -> String?) {
J'y ai pensé mais je me suis dit que puisqu'il y a un ticket JIRA dédié à la migration en général, ce serait l'occasion de séparer cette feature.

2022-11-21 07:56 UTC, henriSedjame commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +        data class FaqProjection(
Oui en effet pourquoi pas

2022-11-22 16:57 UTC, djowalker approved these changes
Semble OK, plus qu'à tester en condition avant de merge

2022-12-09 08:47 UTC, djowalker commented
@assouktim du coup c'est mergé ?

2022-12-20 14:56 UTC, djowalker commented
Code déjà mergé en PROD et dispo en contribution : 
https://github.com/theopenconversationkit/tock/pull/1426

2022-12-20 14:56 UTC, closed without merging