1337 add an i advize connector
CreditMutuelArkea/tock pull request #14
Opened 2022-04-13 09:45 UTC by davhamelin

Ajout d'un connector iAdvize basic

2022-04-13 15:41 UTC, djowalker commented on bot/connector-iadvize/src/main/kotlin/model/response/conversation/Duration.kt
> +        millis, secondes, minutes
Pourquoi pas en anglais ?

2022-04-13 15:42 UTC, djowalker commented on bot/connector-iadvize/src/main/resources/META-INF/services/ai.tock.bot.connector.ConnectorProvider
> +# Copyright (C) 2017/2021 e-voyageurs technologies
Répétitions triplée de la licence

2022-04-13 17:04 UTC, davhamelin commented on bot/connector-iadvize/src/main/resources/META-INF/services/ai.tock.bot.connector.ConnectorProvider
> +# Copyright (C) 2017/2021 e-voyageurs technologies
corrigé

2022-04-13 17:05 UTC, davhamelin commented on bot/connector-iadvize/src/main/kotlin/WebhookActionConverter.kt
> +        //val eventState = message.getEventState()
oublier lors du copier coller de la classe dont je me suis inspiré (le GAConnector)

2022-04-13 17:10 UTC, davhamelin commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnectorCallback.kt
> +            if (!answered) {
Le principe c'est que, l'engine produit des addAction, un eventAnswered, mais parfois aussi un sendResponse.
Le problème, c'est que le eventAnswered produit lui aussi un sendResponse.
le comportement de "if (!answered)" à été récupéré du GAConnector. Au début je ne l'avais pas garder, pense qu'il s'agissait d'une spécificité, mais en testant le iAdvizeConnector j'ai vu remonté dans les log des erreur "already answered". C'est là que j'ai regarder plus en détail de fonctionnement de l'engine, et que j'ai identifé ce problème et ce besoin de ne traité qu'une seul fois le "sendResponse" (c'est peut être une évolution de l'engine qui avant ne produisait pas lui même le sendResponse ... je ne saurais le dire)

2022-04-13 17:10 UTC, davhamelin commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnector.kt
> +            else -> null
en effet, j'ai corrigé pour ne plus avoir de null

2022-04-13 17:12 UTC, davhamelin commented on bot/admin/web/angular.json
> +    "analytics": "e20323c0-832b-456b-b1ab-076eabfce805"
j'ai appliqué un pull, c'est peut être arrivé à ce moment là ? mais en effet, je ne vois pas pourquoi ce fichier à été modifier.
c'est peut être une fausse manip de ma part

2022-05-09 11:59 UTC, davhamelin commented on bot/admin/web/angular.json
> +  },
Je ne sais pas pourquoi ça ajoute cette ligne à chaque fois ... je la re-retirerais

2022-06-22 15:46 UTC, djowalker commented
Mergé pour test dans `release/sprint_28_iadvize_faq` actuellement.
Voir pour faire une branche de `contribtion/iadvize` avec celle-ci et les quick replies

2022-06-22 17:05 UTC, djowalker requested changes
Des petits nommages à revoir mais sinon OK

2022-07-08 12:10 UTC, djowalker commented on bot/connector-iadvize/src/main/kotlin/IadvizeHandler.kt
> + * Copyright (C) 2017/2021 e-voyageurs technologies
2022, je pense que c'est peut-être à voir avec un rebase ?

2022-07-08 12:13 UTC, djowalker commented on bot/connector-iadvize/src/main/kotlin/model/request/UpdateBot.kt
> +    data class BotId(val idBot: String)
Ici car pas réutilisable ailleurs ? Pourquoi ne pas avoir simplement laissé un String?

2022-07-08 12:16 UTC, djowalker reviewed
globalement OK, une petite question en attendant les derniers retours.

2022-07-08 13:11 UTC, djowalker commented on bot/connector-iadvize/src/main/kotlin/model/request/UpdateBot.kt
> +    data class BotId(val idBot: String)
Vu : car c'est un objet et que c'est le plus simple pour le serializer avec l'api.

2022-07-19 07:38 UTC, djowalker commented on bot/connector-iadvize/src/test/kotlin/IadvizeConnectorTest.kt
> +    //val botDefinition: BotDefinition = mockk(relaxed = true)
Commenté c'est normal ?

2022-07-19 16:24 UTC, davhamelin commented on bot/connector-iadvize/src/test/kotlin/IadvizeConnectorTest.kt
> +    //val botDefinition: BotDefinition = mockk(relaxed = true)
c'est un oubli, j'ai modifier les tests, ce mock n'avait plus lieu d'être.

2022-08-02 09:01 UTC, djowalker approved these changes

2022-08-02 09:01 UTC, djowalker commented on bot/connector-iadvize/src/test/kotlin/IadvizeConnectorTest.kt
> +    fun handlerConversationUnsupport_shouldDontCrash_TockBot() {
shouldNotCrash

2022-09-14 13:45 UTC, davhamelin commented on bot/connector-iadvize/src/test/kotlin/IadvizeConnectorTest.kt
> +    fun handlerConversationUnsupport_shouldDontCrash_TockBot() {
corrigé en dercbot 286

2022-09-14 15:27 UTC, djowalker approved these changes
Juste màj le commentaire sinon ça me paraît OK

2022-09-14 15:27 UTC, djowalker commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnector.kt
>       * if id conversation is in echo, it's an echo : do not treat request.
Comentaire à màj dans ce cas.

2022-09-19 13:07 UTC, closed without merging