Feature/iadvize/derbot 389
CreditMutuelArkea/tock pull request #147
Opened 2023-01-11 10:11 UTC by henriSedjame

- refacto of Iadvize apis
- write some unit tests

2023-01-28 14:19 UTC, Benvii requested changes
Just noticed I forgot to submit the review yesterday.

Thanks, quite a huge contribution (especially due to the iAdvize client), I added a few comments, let's discuss them if you need it.

2023-01-28 14:19 UTC, Benvii commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/graphql/IadvizeGraphQLClient.kt
> +                        if (this@body.hasErrors()) {
You should handle 401, invalid token responses here and try to refresh the token (one time), resend the request. This will prevent any token revoked issue and time computation delta with the expiration date (see my other comment in iAdvizeAuthenticationClient.kt

2023-01-30 07:08 UTC, henriSedjame commented on bot/connector-iadvize/pom.xml
> +            <groupId>com.google.api.grpc</groupId>
J'en ai aucune idée, c'est pas moi qui l'ai rajouté

2023-01-30 07:11 UTC, henriSedjame commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/errors.kt
> +fun authenticationFailedError(): Nothing = throw AuthenticationFailedError()
C'est comme la function error() de kotlin, aucune confusion quant à son utilisation. Il est assez facilement compréhensible que si le nom de la fonction finit par Error(), c'est que c'est dernière lève une exception.

2023-01-30 07:26 UTC, henriSedjame commented on bot/connector-iadvize/src/main/resources/iadvize.properties
> +tock_iadvize_secret_token=IAdvize secret token
A voir avec Jean-Yves

2023-01-30 07:27 UTC, henriSedjame commented on iadvize-client/pom.xml
> +    <artifactId>tock-bot-iadvize-client</artifactId>
Je le renommerai alors tock-iadvize-client. Il n'a rien à faire dans le dossier bot

2023-01-30 07:48 UTC, henriSedjame commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnector.kt
> +        logRequest("GET", "/external-bots")
Ces ajouts de logs ne sont pas de mon fait, j'ai récupéré le code existant. Mais je vais les supprimer parce que je vois qu'une autre implémentation a été aussi ajoutée pour loguer le contexte de la requête, donc on a un doublon

2023-01-30 07:50 UTC, henriSedjame commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnectorCallback.kt
> +                val configuredMessage: String = properties.getProperty(UNSUPPORTED_MESSAGE_REQUEST, UNSUPPORTED_MESSAGE_REQUEST)
Alors ça il faut voir ça avec Jean-Yves.

2023-01-30 07:51 UTC, henriSedjame commented on bot/connector-iadvize/src/main/resources/IadvizeQueryProjects.graphql
> +    projects {
En effet ils servent plus à rien. Je les supprimerai

2023-01-30 07:51 UTC, henriSedjame commented on bot/connector-iadvize/src/main/resources/IadvizeQueryRoutingRule.graphql
> +    routingRule(id: $id) {
idem

2023-01-30 07:54 UTC, henriSedjame commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/authentication/IadvizeAuthenticationClient.kt
> +val credentialsProvider = EnvCredentialsProvider()
C'est l'idée, en créant une interface CredentialsProvider. Optons pour l'injection mais par constructeur.

2023-01-30 13:29 UTC, henriSedjame commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/graphql/IadvizeGraphQLClient.kt
> +    fun isClientConnected(conversationId: String): Boolean = this.execute(
J'achète !!

2023-01-30 13:57 UTC, henriSedjame commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnectorProvider.kt
> +    private const val DISTRIBUTION_RULE_UNVAILABLE_MESSAGE = "tock_iadvize_distribution_rule_unavailable"
On pourrait dire ça pour les autres constantes non? On sait très bien que la valeur de la constante n'est pas la valeur mais plutot le libellé de la propriété qui s'y rattache

2023-01-30 14:00 UTC, henriSedjame commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/authentication/IadvizeAuthenticationClient.kt
> +            ?: authenticationFailedError()
Le nom de la me dit explicitement : << je retourne (donc lève) une erreur de type _authenticationFailed_ >>

2023-01-30 16:23 UTC, henriSedjame commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/authentication/IadvizeAuthenticationClient.kt
> +                val time = it.expiresIn?.let { s -> LocalDateTime.now().plusSeconds(s.toLong() - DELAY_SECONDS) }
{
  "data": null,
  "errors": [
    {
      "message": "Insufficient permissions to perform the operation",
      "extensions": {
        "code": 1000
      }
    }
  ]
}

2023-02-01 08:51 UTC, Benvii commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/graphql/IadvizeGraphQLClient.kt
> +                        if (this@body.hasErrors()) {
@henriSedjame Did you create a ticket for it ? Could you add the reference somewhere here

2023-02-01 10:06 UTC, Benvii requested changes

2023-02-01 10:06 UTC, Benvii commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/retrofit.kt
> +        val requestHeaders = request.headers.onEach{ logger.debug("${it.first}: ${it.second}") }
Prefer the following logger call (function argument), because it prevent the string from being concatenated when debug is disable. Arguments are always evaluated so the string concatenation is made each time event when debug is disabled except if you call it with the function based call : 
```
logger.debug { "${it.first}: ${it.second}" }
```

2023-02-01 10:06 UTC, Benvii commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/utils.kt
> +fun booleanProperty(name: String, defaultValue: Boolean = false): Boolean = property(name, defaultValue.toString()).toBoolean()
It's already defined in the shared module, why duplicating it here ? Maybe it's a dependency issue

2023-02-01 10:06 UTC, Benvii commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnectorProvider.kt
> +    private const val DISTRIBUTION_RULE_UNVAILABLE_MESSAGE = "tock_iadvize_distribution_rule_unavailable"
C'est pas faux, ok pour moi.

2023-02-01 10:13 UTC, jygdev commented
@Benvii , @henriSedjame : je confirme qu'il serait préférable de le mettre en anglais

2023-02-01 10:15 UTC, henriSedjame commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/utils.kt
> +fun booleanProperty(name: String, defaultValue: Boolean = false): Boolean = property(name, defaultValue.toString()).toBoolean()
importer tout le module shared juste pour ça, je trouve ça trop.

2023-02-01 10:16 UTC, henriSedjame commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/retrofit.kt
> +        val requestHeaders = request.headers.onEach{ logger.debug("${it.first}: ${it.second}") }
ok

2023-02-01 12:53 UTC, Benvii approved these changes

2023-02-01 12:53 UTC, Benvii commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/authentication/credentials/credentials-provider.kt
> +        fun instance(): CredentialsProvider {
Yes c'est bon 👍️

2023-02-01 12:54 UTC, Benvii commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/utils.kt
> +fun booleanProperty(name: String, defaultValue: Boolean = false): Boolean = property(name, defaultValue.toString()).toBoolean()
Ok vu ensemble je comprend

2023-02-01 12:55 UTC, Benvii commented on bot/connector-iadvize/pom.xml
> +            <groupId>com.google.api.grpc</groupId>
Retiré ok.

2023-02-01 12:57 UTC, Benvii commented
Juste la phrase en anglais qui manque.

2023-02-01 13:34 UTC, Benvii approved these changes
Thanks for the update 👍️

2023-02-01 13:42 UTC, merged