Feature/scenarios/dercbot 370
CreditMutuelArkea/tock pull request #150
Opened 2023-01-19 07:57 UTC by henriSedjame

- add scenario settings [ repetition number ,  redirect story Id]
- take scenario sttings in account while processing user action

2023-01-27 09:53 UTC, djowalker commented on bot/admin/server/src/main/kotlin/verticle/ScenarioSettingsVerticle.kt
> +            blockingJsonPost(PATH,  setOf(TockUserRole.botUser), handler = handlePost)
Les roles ont été vérifiés et ok par JY? Ou ça n'a pas été abordé la partie rôle concernant les interfaces de scénarios ?

2023-01-27 09:53 UTC, djowalker commented on bot/admin/server/src/main/kotlin/verticle/ScenarioSettingsVerticle.kt
> +            blockingJsonPost(PATH,  setOf(TockUserRole.botUser), handler = handlePost)
Sinon RAS

2023-01-27 14:07 UTC, henriSedjame commented on bot/admin/server/src/main/kotlin/verticle/ScenarioSettingsVerticle.kt
> +            blockingJsonPost(PATH,  setOf(TockUserRole.botUser), handler = handlePost)
Par rapport au role, je n'ai en effe pas confirmer avec JY. Je vais le faire et corriger si besoin :)

2023-01-31 18:17 UTC, djowalker requested changes
Des questions et des propositions de modifs.

2023-01-31 18:17 UTC, djowalker commented on bot/engine/src/main/kotlin/engine/config/tickstory/TickAnswerHandler.kt
> +            when (result) {
Si on va plus loin avec d'autres types héritant de la sealed class, ç peut être découpé en fonction.

2023-01-31 18:17 UTC, djowalker commented on bot/dialog-manager/core/src/test/kotlin/ai/tock/bot/processor/TickStoryProcessorTest.kt
> +        TestCase<TickStoryProcessor, ProcessingResult>("process when action is ")
pas sûr si le nom a bien été écrit : "process when action is repeated" plutôt?

2023-01-31 18:17 UTC, djowalker commented on bot/dialog-manager/core/src/test/kotlin/ai/tock/bot/processor/TickStoryProcessorTest.kt
> +    fun `process when unknown intent is detected and unknownAnswerConfig is provided, retryNb is exceeded and redirectStoryId is provided`() {
retryNb a été supprimé, c'est repetitionNb désormais ?

2023-01-31 18:17 UTC, djowalker commented on bot/dialog-manager/core/src/test/kotlin/ai/tock/bot/processor/TickStoryProcessorTest.kt
> +            // exitAction = StateIds.STATE_3.value,
à enlever si oubli

2023-01-31 18:17 UTC, djowalker commented on bot/dialog-manager/integration-tests/src/test/kotlin/ai/tock/bot/TickStoryExecutorTest.kt
> +        ).process(tickUserAction) as Success
Le test generic ne teste que les Success donc ?
(peut-être un peu de mal à cerner si besoin de tester Redirect également dans ce fichier de test)

2023-01-31 18:17 UTC, djowalker commented on bot/engine/src/main/kotlin/engine/config/ConfiguredStoryHandler.kt
> +            botDefinition.stories.first { def ->
Mettre un commentaire peut-être mais ok.

2023-02-01 07:12 UTC, henriSedjame commented on bot/admin/server/src/main/kotlin/verticle/ScenarioSettingsVerticle.kt
> +    fun configure(webVerticle: WebVerticle, front: FrontClient) {
Euh oui en effet je pourrais passer par injection via Kodein, mais je préfère (c'est mon avis) passer la ressource nécessaire à l'exécution de la fonction en paramètre quand celle ci est disponible dans la classe appelante. 
Je vais néanmoins modifier ça pour coller avec le reste

2023-02-01 07:17 UTC, henriSedjame commented on bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/handlingStep.kt
> +/*
Euh, pour des fichiers kotlin qui ne contiennent pas qu'une classe, object ou interface, la règle de nommage n'impose pas de majuscule.

2023-02-01 07:18 UTC, henriSedjame commented on nlp/front/shared/src/main/kotlin/config/ScenarioSettings.kt
> +    val applicationId: Id<ApplicationDefinition>,
Oui je me suis inspiré de FaqSettings et c'est un applicationId, d'autant plus qu'on utilise le wrapper Id<>

2023-02-01 07:19 UTC, henriSedjame commented on nlp/front/shared/src/main/kotlin/config/ScenarioSettings.kt
> +     * Faq creation date
Oui en effet, je corrige

2023-02-01 07:19 UTC, henriSedjame commented on nlp/front/shared/src/main/kotlin/config/ScenarioSettings.kt
> +     * Faq update date
idem

2023-02-01 07:20 UTC, henriSedjame commented on bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/processingresults.kt
> +package ai.tock.bot.processor
non pas forcément

2023-02-01 07:22 UTC, henriSedjame commented on bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/processingresults.kt
> +data class Success(val session: TickSession, val isFinal: Boolean) : ProcessingResult()
Euh non, j'y ai pensé mais c'est à mon sens pas nécessaire parce que le traitement (direct) du résultat pas la suite ne diffère pas en fonction de la valeur de l'attribut isFinal

2023-02-01 07:24 UTC, henriSedjame commented on bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/TickStoryProcessor.kt
> +        handlingStep = if (handlingStep.action == secondaryObjective) {
Mauvaise idée! Le bloc en question a un return de la fonction process()

2023-02-01 07:27 UTC, henriSedjame commented on bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/processingresults.kt
> +sealed class ProcessingResult
C'est le résultat du processing, pourquoi le nommer type? Le fait d'avoir une sealed class signifie déjà que cette classe peut être de plusieurs types

2023-02-01 07:31 UTC, henriSedjame commented on bot/engine/src/main/kotlin/engine/config/tickstory/TickAnswerHandler.kt
> +            when (result) {
Je ne vois pas vraiment l'intérêt ici. Extraire dans des fonctions séparées la gestion de chaque type de result, oui quand la fonction ne se résume pas en une ligne de code, mais c'est ce qui est déjà fait

2023-02-01 07:32 UTC, henriSedjame commented on bot/dialog-manager/core/src/test/kotlin/ai/tock/bot/processor/TickStoryProcessorTest.kt
> +        TestCase<TickStoryProcessor, ProcessingResult>("process when action is ")
Oui en effet il manquait quelque chose

2023-02-01 07:33 UTC, henriSedjame commented on bot/dialog-manager/core/src/test/kotlin/ai/tock/bot/processor/TickStoryProcessorTest.kt
> +    fun `process when unknown intent is detected and unknownAnswerConfig is provided, retryNb is exceeded and redirectStoryId is provided`() {
Oui en effet, je corrige

2023-02-01 07:33 UTC, henriSedjame commented on bot/dialog-manager/core/src/test/kotlin/ai/tock/bot/processor/TickStoryProcessorTest.kt
> +            // exitAction = StateIds.STATE_3.value,
En effet c'est un oubli, j'enlève

2023-02-01 07:36 UTC, henriSedjame commented on bot/dialog-manager/integration-tests/src/test/kotlin/ai/tock/bot/TickStoryExecutorTest.kt
> +        ).process(tickUserAction) as Success
Sur le dernier test ...
```
  val checkResult: TConsumer<ProcessingResult?> = {
            assertNotNull(it)
            assert(it is Redirect)
        }
```

2023-02-01 07:38 UTC, henriSedjame commented on bot/engine/src/main/kotlin/engine/config/ConfiguredStoryHandler.kt
> +            botDefinition.stories.first { def ->
Le code est plutôt simple à comprendre là je trouve

2023-02-01 09:24 UTC, djowalker commented on bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/TickUnknownHandler.kt
>                              Else set the step to null and return the exitAction of the answerConfig
Penser à màj le commentaire ? (techniquement on c'est toujours une exitAction mais le nom a été renommée)

2023-02-01 09:28 UTC, djowalker commented on nlp/front/shared/src/main/kotlin/config/ScenarioSettings.kt
> +    val applicationId: Id<ApplicationDefinition>,
Je tagge @assouktim juste pour vérifier mon incertitude, si ya pas un soucis de branche ou si au contraire je m'interroge pour rien.

2023-02-01 09:29 UTC, djowalker reviewed
Ok, juste une vérif pour les settings dont je suis pas sûr à 100%

2023-02-01 09:31 UTC, djowalker approved these changes
Juste une vérif de la part d' @assouktim mais ok pour moi sinon.
Voir quand et comment le merge si ya des soucis.

2023-02-01 09:36 UTC, djowalker commented on bot/dialog-manager/integration-tests/src/test/kotlin/ai/tock/bot/TickStoryExecutorTest.kt
> +        ).process(tickUserAction) as Success
Oui mais dans ce fichier on est d'accord que ton processAndCheck ne concerne que les Success ?

2023-02-01 13:43 UTC, closed without merging