Feature/bot api/dercbot 396 397 409
CreditMutuelArkea/tock pull request #155
Opened 2023-01-27 15:41 UTC by djowalker

TODO ; A merger sur une branche adéquate qui servira de livraison. (merge des deux features concernant l'ajout de données complémentaire accessibles depuis le ClientBus du BotApi)

Explication du travail réalisé avec l'ajout d'informations transmises avec les actions et pour les metadatas avec le header.

![drawio-BOTBUS to ClientBus drawio](https://user-images.githubusercontent.com/22080627/215126403-3ca3fdad-2d40-4e74-8565-04906cba40ee.png)

Création d'un README sur le module `tock-bot-api-service` et explication des variables d'environnement.
Ajout d'une propriété supplémentaire dans le README.md 

Propriétés : 
- pour gérer l'ajout des actions dans les requêtes : tock_bot_api_actions_history_to_client_bus à true
- pour ajouter les metadatas présents dans les headers :  tock_web_connector_use_extra_header_as_metadata_request à true

2023-01-30 10:34 UTC, henriSedjame approved these changes

2023-01-30 13:31 UTC, Benvii requested changes
Good PR thanks 👍️, small minor fix can be done.
I know there are no tests for the web connector, if we want to test this feature it would required complex testing, registering a mocked controller with a mocked router then calling the handlers. It would be more a integration test, like mentioned here : https://stackoverflow.com/a/59397431 

Unfortunately I'm not sure we have the time for it.

About the dependency issue I noticed that RequestContext.kt (in bot API model), already rely on `ai.tock.bot.engine.user.PlayerId` so on the engine that is required when using the bot client, sadly.
I think we need to create a ticket about that on the tock side. Some model dataclass should be in a separate model.

2023-01-30 13:31 UTC, Benvii commented on bot/connector-web/src/main/kotlin/WebConnector.kt
> +                val headerSearch = requestInfos.headers(it)
You can use `requestInfos.firstHeader(it)` instead, so that you can remove the 2 following lines it's already implemented.

2023-01-30 14:19 UTC, djowalker commented on bot/connector-web/src/main/kotlin/WebConnector.kt
> +                val headerSearch = requestInfos.headers(it)
A check with a `let` to be sure it is not empty or null is still needed because firstHeader returns a String?

2023-01-30 14:22 UTC, Benvii commented on bot/connector-web/src/main/kotlin/WebConnector.kt
> +                val headerSearch = requestInfos.headers(it)
I was more thinking of the following lines getting index 0 of the list, it's already done by firstHeader but yes you will still need to check if it's null or not.

2023-01-30 14:23 UTC, Benvii commented on bot/api/model/src/main/kotlin/RequestContext.kt
> +typealias ActionsHistory = List<ActionReport>
Closing this we will improve it if need with new feature as discussed today.

2023-01-30 14:25 UTC, djowalker commented on bot/api/model/src/main/kotlin/RequestContext.kt
> +typealias ActionsHistory = List<ActionReport>
To transfer the stories it would be necessary to create a specific DTO for `StoryDefinition` or implementation on botApi side. On the Dialog object it is available only on `tock-bot-engine`. 
Otherwise the deserialization is not working properly because botApi cannot know wich implementation to use for StoryDefinition.

2023-01-30 15:23 UTC, djowalker commented
We now need to create a release branch to effectively merge the code

2023-02-01 08:35 UTC, Benvii approved these changes
Its good 👍️

2023-02-06 08:13 UTC, Benvii approved these changes
Thanks for adding the tests 👍️

2023-02-06 11:23 UTC, djowalker commented
Move to feature/send-mail/develop

2023-02-06 11:23 UTC, closed without merging

2023-02-06 12:26 UTC, Benvii commented
Can you also push a PR as contribution to TOCK repository ?