Feature/scenarios/local installation further documentation
CreditMutuelArkea/tock pull request #162
Opened 2023-02-03 16:25 UTC by djowalker

Petite doc à tester pour pouvoir lancer en local l'interface de scénarios.
Ici on n'est pas en python env.

2023-02-06 10:12 UTC, Benvii commented
Je vais prendre le temps de regarder ça, ça me permettra de voir comment tourne la branche scénario cette après midi.

2023-02-06 13:30 UTC, djowalker commented
Mon env python était installé en sudo donc j'ai dû faire quelques chown et chmod pour donner des droits à mon user, là la plupart des commandes sont dans le cas où on est un user normal.

2023-02-06 17:50 UTC, Benvii requested changes
Tested and I ran my first tick story 🎉

2023-02-06 17:50 UTC, Benvii commented on bot/dialog-manager/core/README.md
>  - `pip install numpy`
you can add it to the requirements.txt file  : 
```
numpy==1.24.2
```

2023-02-06 17:50 UTC, Benvii commented on bot/dialog-manager/core/README.md
> +Below these instructions, we are not using python environments.
I have tested it in a python venv it works. But it requires PATH to be set in intelij environement variable to include the virtual env so that the correct python interpretor is used.

2023-02-06 17:50 UTC, Benvii commented on bot/dialog-manager/core/README.md
> +`-Djava.library.path=/usr/local/lib/python3.8/dist-packages/jep`
It works but it introduce change in the IDE configuration that can't be committed. I don't have any better way for now maybe we should discuss it.
We could maybe try using the JVM option file :  https://www.jetbrains.com/help/idea/tuning-the-ide.html#180240bf

2023-02-07 14:02 UTC, Benvii commented on bot/dialog-manager/core/README.md
> +`-Djava.library.path=/usr/local/lib/python3.8/dist-packages/jep`
Can't be used it's too instable if intelji is updated it's overwritten.

2023-02-07 14:07 UTC, Benvii approved these changes

2023-02-08 07:50 UTC, Benvii approved these changes
LGTM

2023-02-08 08:27 UTC, merged