Feature/front/rku/dercbot 193 roles conditioned menu
CreditMutuelArkea/tock pull request #17
Opened 2022-04-14 13:21 UTC by rkuffer

2022-04-20 09:59 UTC, djowalker requested changes

2022-04-20 09:59 UTC, djowalker commented on nlp/admin/web/src/app/model/auth.ts
> +  faqBotUser,
Doublon faqBotUser

2022-04-20 09:59 UTC, djowalker commented on nlp/admin/web/src/app/core-nlp/auth/auth.guard.ts
> +          } else if (this.userState.hasRole(UserRole.faqNlpUser)) {
Doublon avec les lignes 56-59

2022-04-20 09:59 UTC, djowalker commented on nlp/admin/web/src/app/nlp-admin-app.component.ts
> +  logout(): void {}
Pourquoi ce rajout ?

2022-04-20 09:59 UTC, djowalker commented on nlp/admin/web/src/app/nlp-admin-app.component.ts
> +        hidden: !this.state.hasRole(UserRole.nlpUser)
Cela veut dire que si le user est nlpUser il n'a plus accès à ce menu car il sera caché ?

2022-04-21 07:28 UTC, rkuffer commented on nlp/admin/web/src/app/core-nlp/auth/auth.guard.ts
> +          } else if (this.userState.hasRole(UserRole.faqNlpUser)) {
Je ne vois pas de doublon, ca donne juste un ordre différent dans les checks. J'ai juste choisi de les faire dans le même ordre que l'enum UserRole

2022-04-21 07:32 UTC, rkuffer commented on nlp/admin/web/src/app/model/auth.ts
> +  faqBotUser,
Je n'ai pas ce doublon dans mon code. C'est visiblement le résultat du merge. Je n'avais pas vu que tu avais déjà commencé à modifier le front. Du coup je ne sais pas quoi faire...

2022-04-21 07:55 UTC, rkuffer commented on nlp/admin/web/src/app/model/auth.ts
> +  faqBotUser,
Résolu dans le dernier commit ajouté

2022-04-21 08:35 UTC, rkuffer commented on nlp/admin/web/src/app/nlp-admin-app.component.ts
> +  logout(): void {}
Pour attendre que la réponse du endpoint d'authent soit parvenue à l'appli avant d'évaluer les conditions d'affichage du menu en fonction des rôles, le composant concerné doit s'ajouter en listner du service d'authent `AuthService`. Pour cela il doit implémenter la classe `AuthListener` qui a deux méthodes non optionnelles, `login `et `logout`

2022-04-21 08:37 UTC, rkuffer commented on nlp/admin/web/src/app/nlp-admin-app.component.ts
> +        hidden: !this.state.hasRole(UserRole.nlpUser)
Non, le contraire. Si le user n'est pas nlpUser, il ne verra pas le lien (cf le **!** en début d'expression)

2022-04-21 08:48 UTC, rkuffer commented on nlp/admin/web/src/app/core-nlp/auth/auth.guard.ts
> +          } else if (this.userState.hasRole(UserRole.faqNlpUser)) {
Résolu dans le dernier commit ajouté

2022-04-21 10:06 UTC, brandonsechet approved these changes

2022-04-21 13:24 UTC, djowalker approved these changes

2022-04-29 16:13 UTC, closed without merging