[DERCBOT-412] Fix faq search
CreditMutuelArkea/tock pull request #175
Opened 2023-02-14 13:41 UTC by henriSedjame

2023-02-15 08:50 UTC, djowalker reviewed
Les Tu n'ont pas eu modifs ?

2023-02-15 08:50 UTC, djowalker requested changes

2023-02-15 08:50 UTC, djowalker commented on nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
> +                FaqQueryResult::utterances first   FaqQueryResult::utterances,
attention un espace en trop sur `first`

2023-02-16 08:59 UTC, henriSedjame commented
Non pas de modifs sur les TU

2023-02-17 08:46 UTC, Benvii approved these changes

2023-02-17 09:07 UTC, djowalker approved these changes

2023-02-17 13:15 UTC, merged