feature: Déplacer l'action actuelle "new FAQ" et les futurs actions d…
CreditMutuelArkea/tock pull request #19
Opened 2022-04-14 18:59 UTC by vvilerio

Déplacer l'action actuelle "new FAQ" et les futurs actions d'import / export du bloc de filtre et le placer au niveau du titre de la page

2022-04-20 10:02 UTC, djowalker requested changes

2022-04-20 10:02 UTC, djowalker commented on bot/admin/web/package.json
> +    "node": "14.19.0"
A quoi ça sert, ça force la version de node ? 
Si oui ne devrait pas faire partie du commit.

2022-04-21 07:33 UTC, brandonsechet commented
Je pense qu'il ne faut pas merger le package.json dans cette PR

2022-04-21 12:24 UTC, brandonsechet commented
J'ai laissé un commentaire sur le ticket du JIRA dercbot-227

2022-04-21 12:26 UTC, rkuffer commented on bot/admin/web/package.json
> -    "node-sass": "^4.14.1",
Ceci a déjà été mergé dans master via la PR Fix/front/rku/remove node sass dependency

2022-04-25 12:26 UTC, vvilerio commented on bot/admin/web/package.json
> +    "node": "14.19.0"
c'est une ligne pour utiliser l'outil de gestion de version node , çà s'appel volta, c'est du meme style que nvm

2022-04-26 12:14 UTC, djowalker approved these changes

2022-04-26 12:16 UTC, merged