[DERCBOT-437] Enregistrement des indicateurs liés à une ConfiguredStory
CreditMutuelArkea/tock pull request #205
Opened 2023-03-20 07:52 UTC by henriSedjame

2023-03-20 09:47 UTC, assouktim reviewed
Pas de TU à MAJ ?

2023-03-20 09:47 UTC, assouktim commented on bot/admin/server/src/main/kotlin/BotAdminService.kt
> +            badRequest("Story is not valid : Metrics story must have at least one step that handles at least one metric.")
```suggestion
            badRequest("Story is not valid : Metric story must have at least one step that handles at least one metric.")
```

2023-03-20 09:47 UTC, assouktim commented on bot/admin/server/src/main/kotlin/model/BotStoryDefinitionConfiguration.kt
> +    fun validate() : Boolean {
c'est vaste comme nom, je te propose validateMetrics()

2023-03-20 09:47 UTC, assouktim commented on bot/admin/server/src/main/kotlin/model/BotStoryDefinitionConfiguration.kt
> +    val isMetricStory: Boolean? = false
je pense qu'on peux la mettre obligatoire

2023-03-20 09:47 UTC, assouktim commented on bot/engine/src/main/kotlin/admin/story/StoryDefinitionConfiguration.kt
> +     * True if the story handle metrics
```suggestion
     * True if the story handle metrics and is not a main tracked story
```

2023-03-20 09:47 UTC, assouktim commented on bot/engine/src/main/kotlin/admin/story/StoryDefinitionConfiguration.kt
> +    val isMetricStory: Boolean? = false
idem (required)

2023-03-20 09:50 UTC, djowalker requested changes
Rien de plus que ce qu'a remonté Mohamed

2023-03-20 10:57 UTC, henriSedjame commented on bot/admin/server/src/main/kotlin/model/BotStoryDefinitionConfiguration.kt
> +    val isMetricStory: Boolean? = false
Oui c'est ce que j'ai fait au début, mais lors de génération dans le module mongo-storage, on a une erreur lorsque que la propriété n'est pas nullable.  Je n'arrive pas à comprendre pourquoi mais c'est comme ça (voir bot/storage-mongo/target/generated-sources/kapt/compile/ai/tock/bot/admin/story/StoryDefinitionConfiguration_Serializer.kt)

2023-03-20 10:59 UTC, henriSedjame commented on bot/engine/src/main/kotlin/admin/story/StoryDefinitionConfiguration.kt
> +    val isMetricStory: Boolean? = false
idem

2023-03-21 07:58 UTC, henriSedjame commented on bot/admin/server/src/main/kotlin/model/BotStoryDefinitionConfiguration.kt
> +    val isMetricStory: Boolean? = false
oui oui, ça n'y change rien

2023-03-21 13:32 UTC, assouktim commented on bot/engine/src/main/kotlin/admin/story/StoryDefinitionConfiguration.kt
> +     * True if the story handle metrics
c'est ce flag qui nous permet de dire si la story en cours est la "main tracked" sinon il faut remonter dans l'historique pour choper la "last story"

2023-03-21 13:34 UTC, merged