[DERCBOT-531] Add iAdvize credentials on "AWS Secrets Manager"
CreditMutuelArkea/tock pull request #219
Opened 2023-04-03 16:17 UTC by assouktim

2023-04-04 14:17 UTC, djowalker reviewed
J'aurais pensé qu'on aurait mis tout ça sur gitlark et appelé dans META-INF le bon projet (?)
Et on aurait ajouté dans l'assembly le nouveau module comme ce qui a pu être fait côté CAS

2023-04-05 15:24 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>2.0.7</version>
Voir s'il est possible de récup la version depuis le parent avec : slf4j, qui du coup est actuellement en 2.0.6, même si normalement le scope est bien déterminé à aws-tools

2023-04-05 15:24 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>4.1.0</version>
idem

2023-04-05 15:25 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>1.12.429</version>
variable dispo dans le pom parent normalent ?

2023-04-05 15:25 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>3.0.5</version>
```suggestion
            <version>${kotlin-logging}</version>
```

2023-04-05 15:26 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>1.0.2</version>
```suggestion
            <version>${aws-sdk}</version>
```

2023-04-05 15:26 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>1.12.429</version>
```suggestion
            <version>${aws-sdk}</version>
```

2023-04-05 15:27 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>4.1.0</version>
```suggestion
            <version>${kodein}</version>
```

2023-04-05 15:27 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>4.1.0</version>
```suggestion
            <version>${kodein}</version>
```

2023-04-05 15:27 UTC, djowalker commented on aws-tools/pom.xml
> +            <version>2.0.7</version>
```suggestion
            <version>${slf4j}</version>
```

2023-04-05 15:28 UTC, djowalker commented on aws-tools/src/main/kotlin/ai/tock/aws/secretmanager/dao/SecretAWSDAO.kt
> +                    .withVersionStage("AWSCURRENT")
peut-être en variable de propriété avec une valeur par défaut ?

2023-04-05 15:29 UTC, djowalker commented on aws-tools/src/main/kotlin/ai/tock/aws/secretmanager/dao/SecretDAO.kt
> + * Retrieve secret from a secure source
```suggestion
 * Retrieve secret from a secured source
```

2023-04-05 15:32 UTC, djowalker commented on aws-tools/src/main/kotlin/ai/tock/aws/utils/utils.kt
> +fun property(name: String, defaultValue: String = ""): String = System.getProperty(name) ?: System.getenv(name) ?: defaultValue
C'est dispo dans le tock-shared il me semble ces méthodes non ?

2023-04-05 15:42 UTC, djowalker commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/authentication/credentials/credentials-provider.kt
> +                property(CREDENTIALS_PROVIDER_TYPE), true)
Du coup il faut peut-être une info dans le README.md pour indiquer qu'il faut mettre `AWS`  ou `DEFAULT` selon le type de provider souhaité?

2023-04-05 15:43 UTC, djowalker commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/constants.kt
> +const val CREDENTIALS_PROVIDER_TYPE = "credentials_provider_type"
```suggestion
const val CREDENTIALS_PROVIDER_TYPE = "iadvize_credentials_provider_type"
```

2023-04-05 15:44 UTC, djowalker commented on bot/dialog-manager/handlers-provider-dev-tools/src/main/resources/META-INF/services/ai.tock.iadvize.client.authentication.credentials.CredentialsProvider
> +ai.tock.bot.AWSCredentialsProvider
En fait en théorie on aurait indiqué le souhait dans le META-INF. Mais c'est vrai que configuré comme ça avec le credential_provider_type ça permet d'être modulable pour tout le monde.

2023-04-05 15:48 UTC, djowalker requested changes
Relecture, des suggestions proposées.

2023-04-06 14:42 UTC, assouktim commented on aws-tools/src/main/kotlin/ai/tock/aws/utils/utils.kt
> +fun property(name: String, defaultValue: String = ""): String = System.getProperty(name) ?: System.getenv(name) ?: defaultValue
Le module iAdvize-client ne dépend pas de tock-shared

2023-04-06 15:53 UTC, djowalker commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/constants.kt
> +const val ADVIZE_CREDENTIALS_PROVIDER_TYPE = "iadvize_credentials_provider_type"
```suggestion
const val IADVIZE_CREDENTIALS_PROVIDER_TYPE = "iadvize_credentials_provider_type"
```

faute de frappe probablement

2023-04-06 15:53 UTC, djowalker commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/authentication/credentials/credentials-provider.kt
> +                property(ADVIZE_CREDENTIALS_PROVIDER_TYPE), true)
```suggestion
                property(IADVIZE_CREDENTIALS_PROVIDER_TYPE), true)
```

2023-04-06 15:54 UTC, djowalker commented on iadvize-client/src/main/kotlin/ai/tock/iadvize/client/authentication/credentials/credentials-provider.kt
> +import ai.tock.iadvize.client.ADVIZE_CREDENTIALS_PROVIDER_TYPE
```suggestion
import ai.tock.iadvize.client.IADVIZE_CREDENTIALS_PROVIDER_TYPE
```

2023-04-06 15:55 UTC, djowalker commented on aws-tools/src/main/kotlin/ai/tock/aws/utils/utils.kt
> +fun property(name: String, defaultValue: String = ""): String = System.getProperty(name) ?: System.getenv(name) ?: defaultValue
Yep mais je le voit en dépendance du projet dans le pom donc je me suis posé la question (?)

2023-04-06 15:55 UTC, djowalker commented on aws-tools/pom.xml
> +            <artifactId>tock-shared</artifactId>
besoin du shared en entier ou on peut /doit exclure certains packages?

2023-04-06 15:56 UTC, djowalker requested changes
Petite faute de frappe et question persistante sur la dépendance tock-shared

2023-04-17 08:29 UTC, assouktim commented on aws-tools/pom.xml
> +            <artifactId>tock-shared</artifactId>
En entier oui

2023-04-17 08:41 UTC, Benvii requested changes
Small documentation missing about the provider type.

2023-04-17 15:36 UTC, Benvii approved these changes
Thanks for the update 👍️

2023-04-18 07:42 UTC, merged