[DERCBOT-536] Metrics API
CreditMutuelArkea/tock pull request #229
Opened 2023-04-18 13:17 UTC by assouktim

2023-04-20 09:27 UTC, djowalker commented on bot/admin/server/src/main/kotlin/service/MetricService.kt
> +    private val metricDao: MetricDAO by injector.instance()
```suggestion
    private val metricDao: MetricDAO get() = injector.provide()
```
Pour ne pas avoir les soucis d'injection éventuels rencontrés dans les scénarios côté tests

2023-04-20 09:28 UTC, djowalker commented on bot/admin/server/src/main/kotlin/service/MetricService.kt
> +     * @param filter [MetricFilter] ]the expected indicator name
```suggestion
     * @param filter [MetricFilter] the expected indicator name
```

2023-04-20 09:30 UTC, djowalker commented on bot/engine/src/main/kotlin/admin/indicators/metric/MetricFilter.kt
> + * Copyright (C) 2017/2021 e-voyageurs technologies
Peut-être le copyright à passer à 2023

2023-04-20 09:32 UTC, djowalker commented on bot/engine/src/main/kotlin/engine/config/ConfiguredStoryHandler.kt
> +     * Save a distinct [MetricType.QUESTION_ASKED] metrics
```suggestion
     * Save distinct [MetricType.QUESTION_ASKED] metrics
```

2023-04-20 09:49 UTC, djowalker commented on bot/storage-mongo/src/main/kotlin/indicator/metric/MetricMongoDAO.kt
> +            listOfNotNull(
Possible de faire un méthode qui retourne le Bson avec les filtres
exemple MetricFilter.filterNotNull pour raccourcir l'aggregate, possible de s'inspirer de ce qui est fait dans FaqDefinitionMongoDAO.

2023-04-20 09:51 UTC, djowalker commented on bot/storage-mongo/src/test/kotlin/indicator/metric/MetricAggregationMongoDAOTest.kt
> +        // --------------------CAS 02--------------------------
CASE

2023-04-20 09:51 UTC, djowalker commented on bot/storage-mongo/src/test/kotlin/indicator/metric/MetricAggregationMongoDAOTest.kt
> +        // --------------------CAS 03--------------------------
CASE

2023-04-20 09:51 UTC, djowalker commented on bot/storage-mongo/src/test/kotlin/indicator/metric/MetricAggregationMongoDAOTest.kt
> +        // --------------------CAS 04--------------------------
CASE

2023-04-20 09:51 UTC, djowalker commented on bot/storage-mongo/src/test/kotlin/indicator/metric/MetricAggregationMongoDAOTest.kt
> +        // --------------------CAS 05--------------------------
CASE

2023-04-20 09:52 UTC, djowalker commented on bot/storage-mongo/src/test/kotlin/indicator/metric/MetricAggregationMongoDAOTest.kt
> +        // --------------------CAS 06--------------------------
idem pour les autres

2023-04-20 10:01 UTC, djowalker commented on bot/storage-mongo/src/test/kotlin/indicator/metric/MetricAggregationMongoDAOTest.kt
> +            botId = botId1
Un seul botId pour le coup?

2023-04-20 10:05 UTC, djowalker requested changes
Des propositions mais sinon LGTM

2023-04-21 15:08 UTC, assouktim commented on bot/storage-mongo/src/main/kotlin/indicator/metric/MetricMongoDAO.kt
> +        })), group(id = with(groupBy) {
l'exemple que tu mentionnes utilise l'opération push afin regrouper les datas dans un array, cela n'est pas notre besoin.

2023-04-21 15:15 UTC, assouktim commented on bot/storage-mongo/src/test/kotlin/indicator/metric/MetricAggregationMongoDAOTest.kt
> +            botId = botId1
Cette classe fait focus surtout sur les groupBy, le botId2 est utilisé uniquement dans le test 'filter by botId without grouping'. 
Par contre, il a été couvert par les tests dans une classe de dédié aux CRUD 'MetricMongoDAOTest.kt' que tu ne vois pas dans cette PR.

2023-04-25 09:02 UTC, djowalker commented on bot/admin/server/src/main/kotlin/model/indicator/metric/Mappers.kt
> + * Map an [CustomMetric] to [CustomMetricResponse]
```suggestion
 * Map a [CustomMetric] to [CustomMetricResponse]
```

2023-04-27 08:13 UTC, djowalker approved these changes
LGTM
Thanks !

2023-04-27 09:48 UTC, merged