1168 faq UI with new roles support
CreditMutuelArkea/tock pull request #23
Opened 2022-04-22 15:02 UTC by djowalker

A ne pas merger : Mais permet de voir les différences sur les rôles entre faq_ui et faq_ui with rôles.

2022-04-26 08:16 UTC, djowalker commented on bot/engine/src/main/kotlin/engine/user/UserState.kt
> +        private val disabledDuration = longProperty("tock_bot_disabled_duration_in_minutes", (60 * 24 * 5).toLong())
Ne devrait pas être commité, dû à la version de Kotlin qui s'interprête mal sur Intellij

2022-04-27 13:54 UTC, lerio29 requested changes
Quelques petites choses à modifier.

2022-04-27 13:54 UTC, lerio29 commented on bot/admin/web/src/app/bot-admin-app.component.ts
> +export class BotAdminAppComponent implements AuthListener, OnInit, OnDestroy {
Le AuthListener implémenté est vraiment utilisé ? çà correspond à çà par exemple ?
`this.auth.addListener(this);`  ligne 51

2022-04-27 13:54 UTC, lerio29 commented on bot/admin/web/src/app/test/test-tabs.component.ts
> +    public title: string,
L'ancien formatage était plus lisible je trouve

2022-04-27 13:54 UTC, lerio29 commented on bot/engine/src/main/kotlin/engine/user/UserState.kt
> +        private val disabledDuration = longProperty("tock_bot_disabled_duration_in_minutes", (60 * 24 * 5).toLong())
Pourquoi ne pas typer les variables ?
        exemple : 
private val refreshDuration: Property = longProperty("tock_bot_refresh_profil_duration_in_minutes", (60 * 24 * 5).toLong())

2022-04-27 13:54 UTC, lerio29 commented on nlp/admin/web/src/app/core-nlp/auth/auth.guard.ts
> +      if ((!this.userState.hasRole(UserRole.nlpUser) && url.startsWith(this.rolesMap.get(UserRole.nlpUser)))
Sur les if de ce genre un peu de commentaires çà peut être sympa :)

2022-04-27 13:54 UTC, lerio29 commented on shared/src/main/kotlin/security/auth/PropertyBasedAuthProvider.kt
> +                            context.isAuthorized((faqNlpUser)) { faqNlpUserResult ->
Sur un pavé de ce type un peu de commentaires ou carrément un petit découpage avec des sous-méthodes et de noms bien choisis çà pourrait rendre le tout plus lisible.

2022-04-27 13:54 UTC, lerio29 commented on shared/src/main/kotlin/vertx/WebVerticle.kt
> +import ai.tock.shared.*
les wildcards .*   attention, faut pas en abuser

2022-04-27 14:06 UTC, djowalker commented on bot/admin/test/core/src/main/kotlin/TestCoreService.kt
> +import ai.tock.shared.security.TockUserRole.*
Faut que je regarde la conf de mes imports

2022-04-27 14:39 UTC, rkuffer commented on bot/admin/web/src/app/bot-admin-app.component.ts
> +export class BotAdminAppComponent implements AuthListener, OnInit, OnDestroy {
Tout à fait

2022-04-27 14:43 UTC, rkuffer commented on bot/admin/web/src/app/test/test-tabs.component.ts
> +    public title: string,
Le formatage est désormais délégué à Prettier. Cf .prettierrc.json pour les options définies

2022-04-29 12:16 UTC, djowalker commented on shared/src/main/kotlin/security/auth/PropertyBasedAuthProvider.kt
> +                            context.isAuthorized((faqNlpUser)) { faqNlpUserResult ->
Les commentaires vont être choisis car là on st dans une lamdba et le context a une méthode overloadée donc un peu particulier à gérer

2022-04-29 13:39 UTC, merged