Feature/scenarios/documentation
CreditMutuelArkea/tock pull request #230
Opened 2023-04-18 13:51 UTC by jygdev

Première version de la doc des scénarios

2023-04-20 10:11 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +Il est possible de rechercher un scénario saisissant du texte dans le champ _Search_.
```suggestion
Il est possible de rechercher un scénario en saisissant du texte dans le champ _Search_.
```

2023-04-20 10:14 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +    * _Api handler_ : code métier qui sera exécuté lors de l'exéuction de l'action. L'exécution d'une action comportant un handler ne rend pas la main à l'utilisateur mais déclenche un nouveau round
```suggestion
    * _Api handler_ : code métier qui sera exécuté lors de l’exécution de l'action. L'exécution d'une action comportant un handler ne rend pas la main à l'utilisateur mais déclenche un nouveau round du gestionnaire de dialogue, l’exécution du code métier ayant potentiellement produit de nouvelles informations utiles à l'avancée du scénario 
```

2023-04-20 10:15 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +_State machine_ : machine à états hiérarchique permettant de contrôler le dialogue de manière fine
rajouter un lien wikipédia d'une machine à état hiérarchique ?

2023-04-20 10:16 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +_State machine_ : machine à états hiérarchique permettant de contrôler le dialogue de manière fine
Et / ou Xsate pour cerner ?

2023-04-20 10:18 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +    * _Name_ : nom de l'intention permettant de comprendre la question/réponse qu'aura envoyé l'utilisateur
Pensez à indiquer si les champs sont optionnels ou non ?

2023-04-20 10:19 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +
Pas de screenshot d'exemple lié à scenario_creation.png?

2023-04-20 10:20 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +    * _Target story_ : permet de forcer le switch vers une autre story
screenshot casting Bot Action ?

2023-04-20 10:21 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +    * _Api handler_ : code métier qui sera exécuté lors de l'exéuction de l'action. L'exécution d'une action comportant un handler ne rend pas la main à l'utilisateur mais déclenche un nouveau round
Faudra voir pour une doc de création d'Api Handler et renvoyer dessus ?

2023-04-20 10:22 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +        * soit directement via l'exécution d'un handler qui va produire ce contexte
```suggestion
        * soit directement via l'exécution d'un handler (par exemple un Api handler) qui va produire ce contexte
```

2023-04-20 10:24 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +![schéma Tock](../../../img/scenarios_casting_action.png "Création d'un' scénario - Casting - Action")
Image non poussée ?

2023-04-20 10:24 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +* Les Les nouvelles réponses à envoyer en cas d'incompréhension
```suggestion
* Les nouvelles réponses à envoyer en cas d'incompréhension
```

2023-04-20 10:26 UTC, djowalker requested changes
Oublis de push de screenshots et autre point d'interrogation

2023-04-20 12:48 UTC, jygdev commented on docs/_fr/user/studio/scenarios-management.md
> +    * _Target story_ : permet de forcer le switch vers une autre story
il arrive... :)

2023-04-20 12:48 UTC, jygdev commented on docs/_fr/user/studio/scenarios-management.md
> +![schéma Tock](../../../img/scenarios_casting_action.png "Création d'un' scénario - Casting - Action")
oups

2023-04-20 12:48 UTC, jygdev commented on docs/_fr/user/studio/scenarios-management.md
> +
ah oui pourquoi pas je vais en ajouter

2023-04-20 14:23 UTC, rkuffer commented on docs/_fr/user/studio/scenarios-management.md
> +* Un ensemble de _tags_
Peut-être préciser le role des tags ? (Un ensemble de tags permettant de filtrer l'affichage des scenarios en fonction d'un ou plusieurs tags donnés)

2023-04-20 14:32 UTC, rkuffer commented on docs/_fr/user/studio/scenarios-management.md
> +2- Ajout des phrases d'entrainement et des contextes en sortie : une fois l'intention définie, vous aller pouvoir ajouter des phrases d'entrainement, associer des entités que vous pourrez lier à des
vous aller pouvoir => vous allez pouvoir

2023-04-20 14:35 UTC, rkuffer commented on docs/_fr/user/studio/scenarios-management.md
> +* _Output contexts_ : Associer un contexte en sortie : permet lorsque l'intention est suffisante pour déterminer qu'un contexte peut être créé sans nécessiter la détection d'une entité associée à l'i
permet [de définir un context] lorsque l'intention est...

2023-04-20 14:40 UTC, rkuffer commented on docs/_fr/user/studio/scenarios-management.md
> +> Tips : à retenir pour la modélisation sous forme d'objectif, pour une "boîte" donnée, il doit y avoir une action représentant l'objectif à atteindre ainsi que toutes les actions participant à la ré
compte [tenu] des informations...

2023-04-20 15:52 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +> Tips : à retenir pour la modélisation sous forme d'objectif, pour une "boîte" donnée, il doit y avoir une action représentant l'objectif à atteindre ainsi que toutes les actions participant à la ré
```suggestion
> Tips : à retenir pour la modélisation sous forme d'objectif, pour une "boîte" donnée, il doit y avoir une action représentant l'objectif à atteindre ainsi que toutes les actions participant à la résolution de cet objectif. Au sein d'une "boîte", toutes les transitions (sauf rare exception) ramènent vers l'objectif à atteindre, c'est le solveur du graphe qui déterminera à chaque round de la conversation quelle est la meilleure action à exécuter compte tenu des informations disponibles.  
```

2023-04-20 15:53 UTC, djowalker commented on docs/_fr/user/studio/scenarios-management.md
> +* _Output contexts_ : Associer un contexte en sortie : permet lorsque l'intention est suffisante pour déterminer qu'un contexte peut être créé sans nécessiter la détection d'une entité associée à l'i
```suggestion
* _Output contexts_ : Associer un contexte en sortie : permet de définir un contexte lorsque l'intention est suffisante pour déterminer qu'un contexte peut être créé sans nécessiter la détection d'une entité associée à l'intention (ex : les intentions génériques type 'oui' ou 'non')
```

2023-04-28 12:24 UTC, assouktim commented on docs/_fr/user/studio/scenarios-management.md
> +    * _Api handler_ : code métier qui sera exécuté lors de l'exéuction de l'action. L'exécution d'une action comportant un handler ne rend pas la main à l'utilisateur mais déclenche un nouveau round
on verra, nous avons laissé des exemples dans le code pour la partie dev-tools.

2023-04-28 12:41 UTC, merged