[DERCBOT-609] Scenario designer contextual help
CreditMutuelArkea/tock pull request #250
Opened 2023-06-14 10:51 UTC by rkuffer

2023-06-15 09:05 UTC, djowalker commented on bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.html
> +            nbTooltip="Sends an error message targeted at the question raised by this action if the user's response is not recognized after the action has been executed (intent unknown received)"
pas vraiment considéré comme une message d'erreur si ?
Plus un incompréhension face à l'attendu ?
Après comment le traduire ? -> proposition : `The message send when user send an unexpected or unrecognized message.` (?)

2023-06-15 09:07 UTC, djowalker commented on bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/intent-edit/intent-edit.component.html
> +        nbTooltip="Set of sentences to train intention. Entities can be associated with phrases by selecting a word and clicking on Add entity. You can associate a context with an entity by clicking
```suggestion
        nbTooltip="Set of sentences to train intention. Entities can be associated with phrases by selecting a word and clicking on Add entity. You can associate a context with an entity by clicking on the word and selecting the context to associate. When the user message is received, if the entity is detected, the associated context will be created with the entity's text as its value."
```

2023-06-15 09:09 UTC, djowalker requested changes
Petites propositions.

2023-06-15 13:42 UTC, rkuffer commented on bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.html
> +            nbTooltip="Sends an error message targeted at the question raised by this action if the user's response is not recognized after the action has been executed (intent unknown received)"
On va faire plus simple :
Message sent if the response given by the user following this action is not recognized (unknown intent received).

2023-06-15 13:43 UTC, rkuffer commented on bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/intent-edit/intent-edit.component.html
> +        nbTooltip="Set of sentences to train intention. Entities can be associated with phrases by selecting a word and clicking on Add entity. You can associate a context with an entity by clicking
Moins heureux comme tournure

2023-06-16 09:10 UTC, djowalker approved these changes

2023-06-16 09:23 UTC, merged