[DERCBOT-655] new predefined intent - tock:ragexcluded
CreditMutuelArkea/tock pull request #258
Opened 2023-07-28 09:10 UTC by assouktim

2023-07-31 12:19 UTC, djowalker commented on bot/engine/src/main/kotlin/admin/bot/RAGConfiguration.kt
> +val RAG_ENABLED: Boolean =booleanProperty("RAG_ENABLED", false)
```suggestion
val RAG_ENABLED: Boolean =booleanProperty("tock_rag_enabled", false)
```

2023-07-31 12:23 UTC, djowalker commented on bot/engine/src/main/kotlin/definition/BotDefinition.kt
> +                        ragexcluded.intentWithoutNamespace().name -> ragExcludedStory ?: unknownStory
check si rag enabled également ?

2023-07-31 12:27 UTC, djowalker commented on nlp/front/service/src/main/kotlin/ApplicationConfigurationService.kt
>          // 2 create entities where there are not present in the new intent (except if it's the unknown intent)
```suggestion
        // 2 create entities where there are not present in the new intent (except if it's the unknown or rag_excluded intent)
```

2023-07-31 12:32 UTC, djowalker commented on nlp/admin/server/src/main/kotlin/AdminService.kt
> +            if (intentWithNamespace == UNKNOWN_INTENT_NAME) UNKNOWN_INTENT_NAME.toId()
peut-être utile d'utiliser un when ?

2023-07-31 12:33 UTC, djowalker commented on bot/engine/src/main/kotlin/definition/BotDefinition.kt
> +                        ragexcluded.intentWithoutNamespace().name -> ragExcludedStory ?: unknownStory
Pas besoin car à priori géré dans finStoryDefinition L164

2023-07-31 12:34 UTC, djowalker commented on bot/engine/src/main/kotlin/definition/BotDefinition.kt
> +    val defaultRAGExcludedAnswer: I18nLabelValue
```suggestion
    val defaultRagExcludedAnswer: I18nLabelValue
```

2023-07-31 12:38 UTC, djowalker commented on bot/engine/src/main/kotlin/definition/BotDefinition.kt
> +            else null
as-t-on réellement besoin de renvoyer null car la valeur par défaut est null (?)

2023-07-31 12:38 UTC, djowalker commented on bot/engine/src/main/kotlin/engine/config/BotDefinitionWrapper.kt
> +                    if(ragConfigurationEnabled) ragExcludedStory else null
as-t-on réellement besoin de renvoyer null car la valeur par défaut est null (?)

2023-07-31 12:44 UTC, djowalker commented on bot/engine/src/main/kotlin/engine/config/BotDefinitionWrapper.kt
> +            if (i2 == ragexcluded) BotDefinition.findIntent(stories, intent) else i2
Pas certain de la gestion si c'est désactivé ?

2023-07-31 12:45 UTC, djowalker requested changes
Quelques questions et suggestions

2023-08-03 13:18 UTC, djowalker commented on nlp/admin/server/src/main/kotlin/model/UpdateSentencesQuery.kt
> +    val rageExcludedNewIntent: Boolean get() = RAG_EXCLUDED_INTENT_NAME == newIntentId?.toString()
```suggestion
    val ragExcludedNewIntent: Boolean get() = RAG_EXCLUDED_INTENT_NAME == newIntentId?.toString()
```

2023-08-03 16:10 UTC, djowalker commented
La difficulté est bel et bien de gérer lorsqu'on active/ désactive la story. Sera géré dans un autre ticket.

2023-08-21 13:03 UTC, assouktim commented on bot/engine/src/main/kotlin/definition/BotDefinition.kt
> +            else null
ici, le null c'est pour le else, sinon ça compile pas

2023-08-21 15:29 UTC, djowalker approved these changes
LGTM

2023-08-28 13:53 UTC, merged