[DERCBOT-768] LLM Orchestrator - Check setting API
CreditMutuelArkea/tock pull request #283
Opened 2023-12-05 16:32 UTC by assouktim

2023-12-07 10:18 UTC, assouktim commented
I think we should rename the **_LLM Orchestrator_** project to **_AI Orchestrator_**.

2023-12-21 12:47 UTC, Benvii requested changes
Check settings, invocation part and vector generation of a test string can be in the abstraction layer as they will always be the same

2023-12-21 12:48 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/errors/error_factories.py
> +def create_error_info_openai(exc: APIError, provider: str) -> ErrorInfo:
Ok I just saw that APIError is from openai, maybe it should be located in an openai specific file ?

2023-12-22 09:35 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/models/errors/errors_models.py
> +class ErrorCode(Enum):
Committed

2023-12-22 09:42 UTC, Benvii approved these changes
Thanks for this good rand rich PR, it's good for me, don't hesitate to check my small commit about the enum documentation.

2023-12-26 10:07 UTC, merged