[DERCBOT-805] IA Orchestrator Client & Validation RAG
CreditMutuelArkea/tock pull request #284
Opened 2023-12-11 16:02 UTC by assouktim

2023-12-13 13:09 UTC, assouktim commented
/!\ Do not merge on rag/dercbot-768 /!\

2023-12-21 14:35 UTC, Benvii requested changes
- [x]  Naming AIOrchestrator may be confusing as we have AI in NLP API, maybe genAiOrchestrator is best suited
- [x] Stick to snake_case for the API but configure retro fit to do the conversion

2023-12-21 15:42 UTC, assouktim commented on llm/orchestrator-core/src/main/kotlin/ai/tock/llm/orchestrator/core/models/em/EMSetting.kt
>      val provider: LLMProvider,
ah yes, I had started to do it, I created the missing enum, but I didn't use it

2023-12-22 14:21 UTC, Benvii approved these changes
LGTM

2023-12-22 14:25 UTC, Benvii requested changes
Camel case VS Snake Case still need to be done in retrofit.

2023-12-22 14:26 UTC, Benvii commented on llm/orchestrator-core/src/main/kotlin/ai/tock/llm/orchestrator/core/models/em/EMSetting.kt
>      val provider: LLMProvider,
ok

2023-12-22 14:39 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/models/em/em_setting.py
> +        alias="apiKey"
WIP

2023-12-26 13:48 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/models/em/em_setting.py
> +        alias="apiKey"
it's done

2024-01-03 08:08 UTC, Benvii approved these changes
Thanks it's ok

2024-01-03 08:33 UTC, merged