[DERCBOT-767] AI Orchestrator API - RAG
CreditMutuelArkea/tock pull request #286
Opened 2023-12-21 13:58 UTC by assouktim

/!\ Do not merge on derbot-767 /!\

2024-01-03 14:40 UTC, Benvii requested changes
Great PR, some comments / stuff to improve.
We should probably discuss the debug response format and database settings (if we constraint them or not).

The callback need to be changed and should record only what we want to keep I.

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
> +    document_search_params: Any = Field(
Consumer of this API will be able to pass any parameter the want, in langchain vectorstores.py they are documented as follow : 
```
search_kwargs (Optional[Dict]): Keyword arguments to pass to the
                search function. Can include things like:
                    k: Amount of documents to return (Default: 4)
                    score_threshold: Minimum relevance threshold
                        for similarity_score_threshold
                    fetch_k: Amount of documents to pass to MMR algorithm (Default: 20)
                    lambda_mult: Diversity of results returned by MMR;
                        1 for minimum diversity and 0 for maximum. (Default: 0.5)
                    filter: Filter by document metadata
```

For OpenSearch exetended parameters are the following defined in opensearch_vector_search.py (similarity_search method) : 
```python
"""
Args:
            query: Text to look up documents similar to.
            k: Number of Documents to return. Defaults to 4.

        Returns:
            List of Documents most similar to the query.

        Optional Args:
            vector_field: Document field embeddings are stored in. Defaults to
            "vector_field".

            text_field: Document field the text of the document is stored in. Defaults
            to "text".

            metadata_field: Document field that metadata is stored in. Defaults to
            "metadata".
            Can be set to a special value "*" to include the entire document.

        Optional Args for Approximate Search:
            search_type: "approximate_search"; default: "approximate_search"

            boolean_filter: A Boolean filter is a post filter consists of a Boolean
            query that contains a k-NN query and a filter.

            subquery_clause: Query clause on the knn vector field; default: "must"

            lucene_filter: the Lucene algorithm decides whether to perform an exact
            k-NN search with pre-filtering or an approximate search with modified
            post-filtering. (deprecated, use `efficient_filter`)

            efficient_filter: the Lucene Engine or Faiss Engine decides whether to
            perform an exact k-NN search with pre-filtering or an approximate search
            with modified post-filtering.

        Optional Args for Script Scoring Search:
            search_type: "script_scoring"; default: "approximate_search"

            space_type: "l2", "l1", "linf", "cosinesimil", "innerproduct",
            "hammingbit"; default: "l2"

            pre_filter: script_score query to pre-filter documents before identifying
            nearest neighbors; default: {"match_all": {}}

        Optional Args for Painless Scripting Search:
            search_type: "painless_scripting"; default: "approximate_search"

            space_type: "l2Squared", "l1Norm", "cosineSimilarity"; default: "l2Squared"

            pre_filter: script_score query to pre-filter documents before identifying
            nearest neighbors; default: {"match_all": {}}
"""
```

I'm not sure of one of those parameters could represent any security flow 🤔, should we let the API consumer change / tune all of that ? is it really safe ? Or should we limit them a more safer constraint format ?

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/responses/responses.py
> +    debug: Optional[Any] = Field(
This means that the debug might be an object and not a list  of objects, we don't really know it's format for now, what we know is that debug information will / may contain the follow data : 

- debugging trace ID (langfuse ID)
- rephrased question, this could also be at a higher level in RagResponse
- documents content + reference / link (until we don't have langfuse)
- prompts : rephrasing ? and retrieve  + QA  prompt

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/callbacks/retriever_json_callback_handler.py
> +        self.records: Dict[str, Any] = {
As mentioned for the poc record shouldn't by ordered by event name, their execution order is important, classifying them by event destroy their triggering order and makes it difficult to understand them.

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/callbacks/retriever_json_callback_handler.py
> +class RetrieverJsonCallbackHandler(BaseCallbackHandler):
I'm thinking that we should probably have a much more simple callback handler. The idea is to keep at least / most those data : 

- rephrased question (simply accessible in the debugging data)
- documents : all details as we need to see how the are splited, so we need document content
- prompts : 
  - rephrasing prompt (if used may be null / None)
  - QA prompt

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/settings.py
> +class Settings(BaseSettings):
Add a model_config to prefix all environment variable with `tock_` prefix like this : 

```python
class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix='tock_orchestator_', case_sensitive=True)
```

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/settings.py
> +    AWS = 'AWS'
It can't find where it's used ?

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/rag_chain.py
> +        debug=(None, records_callback_handler.show_records())[debug],
I think we should clearly discuss the format see my other comment, records splited by event is really complexe to handle after for tock we could have a simplified format, keeping in mind that we only need a few details other details will then by store in langfuse.

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/factories/vector_stores/vectore_store.py
> +    CHROMA = 'CHROMA'
Remove it as it's not implemented yet

2024-01-03 14:40 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/rag_chain.py
> +# requests_log.propagate = True
We should have a logger factory with logging yaml configuration file in the POC we made see langchain-conversationnal-qa-cmx / langchain-conversationnal-qa-cmx / langchain_covnersationnal_qa_cmx / config / logging.yaml

This yaml would then be override in the docker file if needed.

2024-01-03 15:27 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/settings.py
> +    AWS = 'AWS'
it is no longer used

2024-01-03 15:35 UTC, assouktim commented on llm/orchestrator-server/pom.xml
> +            <!-- TODO MASS -->
Oops ! 
The TODO consists in restoring the code.

2024-01-03 15:44 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/responses/responses.py
> +    debug: Optional[Any] = Field(
Yes, the debug will be the return of the CallbackHandler.
We could potentially work on the handler's return to aggregate other info, and remap the whole thing into a single return object. I had thought that the work done on the poc was complete. If we need to touch this up, we'll have to do it outside this ticket so as not to block this PR.

2024-01-03 15:46 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/callbacks/retriever_json_callback_handler.py
> +        self.records: Dict[str, Any] = {
Yes i see. We need to keep working on that, but outside of this PR I think

2024-01-03 15:47 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/callbacks/retriever_json_callback_handler.py
> +class RetrieverJsonCallbackHandler(BaseCallbackHandler):
idem

2024-01-03 15:47 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/rag_chain.py
> +        debug=(None, records_callback_handler.show_records())[debug],
idem

2024-01-03 15:59 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
> +    document_search_params: Any = Field(
yes, we can have one object (per type of vector store), but we'll have to do the mapping manually. This mapping must manage all possible search parameters. I'm not sure this is the right solution.

2024-01-05 07:53 UTC, Benvii commented on bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
> +                BotRAGConfigurationDTO(RagService.saveRag(configuration))
Thanks vu avec @morgandiverrez hier en effet

2024-01-05 14:14 UTC, Benvii requested changes
We will discuss remaining comments.

2024-01-05 14:14 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/callbacks/retriever_json_callback_handler.py
> +class RetrieverJsonCallbackHandler(BaseCallbackHandler):
Issue created DERCBOT-824 resolving this thread.

2024-01-05 14:14 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/configurations/logging/logger.py
> +application_logger = logging.getLogger('llm_orchestrator')
Each file should create it's logger if we want to be able to filter subpackage loggings. We will discuss it orally.

2024-01-05 14:14 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
Resolved

2024-01-05 14:14 UTC, Benvii commented on llm/orchestrator-server/pom.xml
> +            <!-- TODO MASS -->
Resolved

2024-01-05 14:14 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/responses/responses.py
> +    debug: Optional[Any] = Field(
Will be treated in DERCBOT-824

2024-01-05 14:14 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
> +    document_search_params: Any = Field(
I'm a bit worried that we are potentially create a security hole allow "unconstrained" parameter that could damage de database, as it can be defined by the API consumer.
We should discuss it as it will have impact on the Rag Settings also.

2024-01-05 14:38 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
> +    document_search_params: Any = Field(
Todo, restraint it to the only 2 parameters used for opensearch.

2024-01-05 17:09 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
> +    document_search_params: Any = Field(
as we saw above, document_search_params is now typed (per the vector store)

2024-01-09 13:58 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/models/vector_stores/open_search/open_search_params.py
> +        description='The OpenSearch boolean query filter. Logical "and" operator is applied.',
Maybe add the url in comment in the description field also.

2024-01-09 13:58 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/rag_chain.py
> +        callbacks=([], [records_callback_handler])[debug],
This isn't easy to read and also not optimal as you are always build a tuple even, prefer a clear ternary operator : 
```suggestion
        callbacks=[records_callback_handler] if debug else [],
```

2024-01-09 13:58 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/rag_chain.py
> +        debug=(None, records_callback_handler.show_records())[debug],
This isn't easy to read and also not optimal as you are always build a tuple even, prefer a clear ternary operator : 
```suggestion
        debug= records_callback_handler.show_records() if debug else None,
```

2024-01-09 13:58 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
> +    document_search_params: Any = Field(
Ok for me it's safer that way.

2024-01-09 13:59 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
> +    document_search_params: Any = Field(
Now typed it's safer for us.

2024-01-09 13:59 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/errors/handlers/openai/openai_exception_handler.py
> -
It's good in the new version 👍️

2024-01-09 14:01 UTC, Benvii requested changes
2 small change required, you use tuple to build optionals it's not really clear for people ready this code

2024-01-10 14:39 UTC, merged