[DERCBOT-814] IA Orchestrator Client - Call RAG & Connect the RAG Story
CreditMutuelArkea/tock pull request #288
Opened 2024-01-03 09:33 UTC by assouktim

/!\ Do not merge on 767 /!\

2024-01-08 13:27 UTC, Benvii commented on bot/connector-rest/src/main/kotlin/RestConnector.kt
> +                            metadata = mapOf("debugEnabled" to message.debugEnabled.toString()),
The idea is to tell that debug is enabled in the response metadata ?

2024-01-08 13:58 UTC, Benvii commented on bot/engine/src/main/kotlin/engine/config/RAGAnswerHandler.kt
> +private val n_lastMessages = intProperty(name="tock_gen_ai_orchestrator_dialog_number_messages", defaultValue = 10)
Those will be configurable in the futur : DERCBOT-825

2024-01-08 14:25 UTC, assouktim commented on bot/connector-rest/src/main/kotlin/RestConnector.kt
> +                            metadata = mapOf("debugEnabled" to message.debugEnabled.toString()),
No, it's a way to tranport this information inside the RAGAnswerHandler

2024-01-09 09:21 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
>  class RagQuery(BaseModel):
To illustrate that prompt in settings and inputs are dependent, you could see if you can describe in pydantic an openapi Object Level exemple, see specification here : https://swagger.io/docs/specification/adding-examples/#:~:text=Object%2Dlevel%20example%3A

2024-01-09 09:29 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
> +            description='Key-value inputs fot the llm prompt when used as a template.',
Add at least in the description that `chat_history` will be override if it's used in the inputs .. I don't think that free form object in OpenAPI spec can have forbidden properties 😬

2024-01-10 14:28 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/requests/requests.py
>  class RagQuery(BaseModel):
This can be done with the following code (also add input parameters with it) : 
```python
    class Config:
        json_schema_extra = {
            'examples': [
                {
                    "question": "How to get started playing guitar ?",
                    "history": [
                        {
                            "text": "Hello, how can I do this?",
                            "type": "HUMAN"
                        },
                        {
                            "text": "you can do this with the following method ....",
                            "type": "AI"
                        }
                    ],
                    "question_answering_llm_setting": {
                        "provider": "OpenAI",
                        "api_key": "ab7***************************A1IV4B",
                        "temperature": 1.2,
                        "prompt": """Use the following context to answer the question at the end.
If you dont know the answer, just say {no_answer}.

Context:
{context}

Question:
{question}

Answer in {locale}:""",
                        "model": "gpt-3.5-turbo"
                    },
                    "embedding_question_em_setting": {
                        "provider": "OpenAI",
                        "api_key": "ab7***************************A1IV4B",
                        "model": "text-embedding-ada-002"
                    },
                    "index_name": "my-index-name",
                    "document_search_params": {
                        "filter": {
                            "term": {
                                "metadata.index_session_id.keyword": "352d2466-17c5-4250-ab20-d7c823daf035"
                            }
                        },
                        "k": 4
                    }
                }
            ]
        }
```

2024-01-10 14:31 UTC, Benvii commented on bot/connector-rest/src/main/kotlin/RestConnector.kt
> +                            metadata = mapOf("debugEnabled" to message.debugEnabled.toString()),
Ok just saw the implementation in RAGAnswerHandler

2024-01-10 14:47 UTC, Benvii requested changes

2024-01-10 14:47 UTC, Benvii commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnector.kt
>              .map { it.identifier }
Use counters here, maybe see also : DERCBOT-741 we can do it here

2024-01-10 14:50 UTC, Benvii commented
We saw this morning the following issues :

- [ ] When None is configured as no answer RAG story setting the value is the string `"null"` not `null`, will be treated on DERCBOT-828

2024-01-11 09:20 UTC, Benvii approved these changes
LGTM ok for merge, ping me after the rebase so that I can approve it.

2024-01-12 10:05 UTC, Benvii approved these changes
Ok for me

2024-01-12 15:01 UTC, merged