Add unit testing + coverage
CreditMutuelArkea/tock pull request #294
Opened 2024-01-16 09:57 UTC by GuirriecP

2024-02-07 12:29 UTC, Benvii requested changes
Main issue is to move files into different folders `integration`, `unit` tests at least.

2024-02-07 12:29 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/tests/test_exception_handlers.py
> +    try:
To test exceptions you should use pytest : 
```python
with pytest.raises(GenAIConnectionErrorException) as gen_exc:
    decorated_function()
assert gen_exc ......
```

See this documentation : https://docs.pytest.org/en/7.1.x/how-to/assert.html

2024-02-07 12:29 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/tests/test_langchain_factory.py
> +    try:
Use pytest.raises

2024-02-12 14:46 UTC, GuirriecP commented on llm/orchestrator-server/src/main/python/app/README.md
> +This will also produce a Coverage.py code coverage report in coverage.xml.
Ajouté dans US à créer.

2024-02-12 14:52 UTC, GuirriecP commented on llm/orchestrator-server/src/main/python/app/README.md
> +### Unit tests
All dev dependencies are listed in poetry.lock, so 'poetry install' will install them along with the app.

2024-02-12 14:58 UTC, GuirriecP commented on llm/orchestrator-server/src/main/python/app/pyproject.toml
>  [tool.poetry.group.dev.dependencies]
Done

2024-02-16 13:43 UTC, GuirriecP commented on llm/orchestrator-server/src/main/python/app/tests/test_configurations.py
> +def test_environment():
I don't understant the comment ;)

2024-02-16 13:48 UTC, GuirriecP commented on llm/orchestrator-server/src/main/python/app/tests/test_em_providers_router.py
The goal of the JIRA there was only to create unit tests, and tests using FastAPI TestClient are meant to be unit tests.
I understand these are not strictly speaking unit tests, but as we don't have functional testing at all, I think it is preferrable to keep them in place to have low-level functional coverage.

2024-02-16 13:49 UTC, GuirriecP commented on llm/orchestrator-server/src/main/python/app/tox.ini
> +    poetry install -v
Yes

2024-02-16 14:09 UTC, GuirriecP commented on llm/orchestrator-server/src/main/python/app/tests/test_exception_handlers.py
> +    try:
Done.

2024-02-16 14:11 UTC, GuirriecP commented on llm/orchestrator-server/src/main/python/app/tests/test_langchain_factory.py
> +    try:
Done

2024-02-19 16:09 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/tests/test_em_providers_router.py
DERCBOT-881

2024-02-19 16:12 UTC, Benvii approved these changes
LGTM

2024-02-20 08:20 UTC, merged