[DERCBOT-686] Use of gunicron + Improve application logging
CreditMutuelArkea/tock pull request #297
Opened 2024-01-19 11:10 UTC by assouktim

gunicorn llm_orchestrator.main:app --reload --bind :8000 --workers=2 --worker-class=uvicorn.workers.UvicornWorker --log-config=~/Code/GitHub/CreditMutuelArkea/tock/llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/configurations/logging/config.ini

2024-01-23 07:37 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/poetry.lock
> +version = "21.2.0"
I've checked on AWS it's the same version for `64bit Amazon Linux 2023 v4.0.6 running Python 3.11`, thanks 👍️

2024-01-24 09:54 UTC, Benvii requested changes
Minor changes required, a more advanced reflexion about contextual logging will need to be done on an other ticket I will create a ticket for that.

Thanks for this PR I'm reflecting the configuration on tock-infra also.

2024-01-24 09:54 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/llm_providers_router.py
> +    logger.info('Start LLM setting check')
Add more details in the logs, such as the provider : 
```suggestion
    logger.info('Start LLM setting check for provider %s', query.setting.provider)
```

2024-01-24 09:54 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/llm_providers_router.py
> +        logger.info('The LLM setting is valid')
I'm afraid that we won't be able to match this log to it's original request and other request associated logs as we don't have contextual logs 😬.
So if we have multiple check requests as the same time we won't be able to distinguish which one is valid and not.

This isn't an issue for the check settings as we will not have a lot of parallel requests, but we should clearly have contextual logging (I don't have any solution in mind). We will create a JIRA for that it's added to the file for creation.

2024-01-24 09:54 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/services/langchain/rag_chain.py
> +        'Yes' if debug else 'No',
```suggestion
        debug,
```

Without condition it will log True or False it's suffisant and prevent that condition for being executed even if debug logs are disabled

2024-01-24 13:57 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/routers/llm_providers_router.py
> +        logger.info('The LLM setting is valid')
DERCBOT-858

2024-02-01 14:44 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/main.py
> +logger.info('Generative AI Orchestrator - Startup')
See suggestion on the updated code.

2024-02-01 16:09 UTC, assouktim commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/main.py
> +logger.info('Generative AI Orchestrator - Startup - Debug logs enabled')
Oops!

2024-02-02 09:47 UTC, Benvii approved these changes
Thanks 👍️

2024-02-02 10:03 UTC, merged