[DERCBOT-686] unique Footnote + improved logging
CreditMutuelArkea/tock pull request #299
Opened 2024-01-23 14:12 UTC by assouktim

2024-01-24 15:50 UTC, Benvii requested changes
Just 1 comment, to make the RAG no answer detection a bit more flexible as we currently experience some issues with it.

2024-01-24 15:50 UTC, Benvii commented on bot/engine/src/main/kotlin/engine/config/RAGAnswerHandler.kt
> +            if (response?.answer?.text == ragConfig?.noAnswerSentence) {
I'm not sure it's best but we should check that the noAnswerSentence is present as a substring of the response ? It would be more flexible and also without case sensitivity using response?.answer?.text?.contains()

2024-01-24 15:50 UTC, Benvii commented on llm/orchestrator-server/src/main/python/app/src/llm_orchestrator/models/rag/rag_models.py
> +        )
Ok for it as we discussed we will probably need in the future the documents (chunk content) but this will be something different from the Foonotes. We will need to think about it in such case it would be interesting to find fragment really used an not all fragment given in the input prompt.

2024-01-25 14:51 UTC, assouktim commented on bot/engine/src/main/kotlin/engine/config/RAGAnswerHandler.kt
> +            if (response?.answer?.text == ragConfig?.noAnswerSentence) {
Yes Im ok to ignore case sensitivity when comparing, but not to check if the response is a substring of the RAG response.

Possible trouble example :
NoAnswerSentence: Sorry I dont know
RAG Answer : "Sorry, I don't know" is a phrase used to apologize.

2024-02-02 09:57 UTC, Benvii commented on bot/engine/src/main/kotlin/engine/config/RAGAnswerHandler.kt
> +            if (response?.answer?.text == ragConfig?.noAnswerSentence) {
Ok good point 👍️

2024-02-02 09:58 UTC, Benvii submitted a review, later dismissed
Ok for me thanks 👍️

2024-02-02 10:15 UTC, merged