[DERCBOT-896] Mapping IAdvizeConnectorMessage on GraphQL mutation + Add RAG start message
CreditMutuelArkea/tock pull request #324
Opened 2024-03-05 13:13 UTC by assouktim

2024-03-08 10:57 UTC, Benvii requested changes
Ok if you just rename the variable as it's not RAG only and we really need to document / comment it as we will remove it in the future and it's a bit "ugly" to path it like that.

2024-03-08 10:57 UTC, Benvii commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnector.kt
> +        if(!ragStartMessage.isNullOrBlank()){
We shouldn't have any rag related stuff in the connector code base rename it proactiveStartMessage as it will be triggered for all proactive "sessions" not only RAG.

Add a comment to explain that this is linked to and iAdvize issue DERCBOT-850,  iAdvize ticket number 119048. Explain that we need it because RAG answers are proactive, really long, we don't have any UX for it so we compensate with this message. It will be removed when the iAdvize issue is fixed.

2024-03-08 10:57 UTC, Benvii commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnectorCallback.kt
> -    fun answerWithoutResponse() = sendResponse()
Is it really unused ? we can still have proactive answer that need a first empty reply ?

2024-03-08 10:57 UTC, Benvii commented on bot/engine/src/main/kotlin/engine/config/AbstractProactiveAnswerHandler.kt
> +            executor.executeBlocking {
Good change 👍️, maybe we should add a delay ? and use 
In saw in behind this that Julien is using vertx.blocking<Unit> (in tock-shared / vertx / VertXs.kt ) that is deprecated, changes are really need on that part.

2024-03-11 10:22 UTC, assouktim commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnectorCallback.kt
> -    fun answerWithoutResponse() = sendResponse()
yes, it's not used, I introduced it as part of the RAG dev, but I noticed that we never send an empty response to iAdvize, we must always send a rich response even with empty replies.

2024-03-11 10:32 UTC, assouktim commented on bot/engine/src/main/kotlin/engine/config/AbstractProactiveAnswerHandler.kt
> +            executor.executeBlocking {
No, there's no need for a delay, the proactive action is already long. It can start immediately after 'startProactiveConversation'.

2024-03-12 13:54 UTC, Benvii commented on bot/connector-iadvize/src/main/kotlin/IadvizeConnectorCallback.kt
> -    fun answerWithoutResponse() = sendResponse()
Ok thanks for the details.

2024-03-12 13:54 UTC, Benvii commented on bot/engine/src/main/kotlin/engine/config/AbstractProactiveAnswerHandler.kt
> +            executor.executeBlocking {
Ok makes sense.

2024-03-12 13:55 UTC, Benvii approved these changes
Ok for me thanks for the renaming good to merge 👍️

2024-03-12 14:07 UTC, merged