feature: aligner le bouton FAQ sur la droite
CreditMutuelArkea/tock pull request #34
Opened 2022-04-29 15:21 UTC by vvilerio

bouton FAQ à droite

2022-04-29 16:11 UTC, djowalker commented
Sur le fonctionnel du bouton c'est OK, par contre sur le fonctionnel lorsqu'on réduit la fenêtre comme le bouton burger à disparu il n'y a plus de bouton pour ajouter une FAQ, et eventuellement les nouveaux boutons d'import/Export qui vont arriver derrière

2022-04-29 16:12 UTC, djowalker requested changes
Lors de la réduction d'écran, le menu burger a éte enlevé mais il n'y a plus de boutons pour ajouter une FAQ

2022-05-05 15:07 UTC, djowalker reviewed
ça me semble OK sur le code mais je remarque toujours que lorsque je réduit l'écran, le bouton NEW FAQ disparait et comme il n'y a plus de menu burger cette action n'est pas dispo lors de la réduction d'écran.

2022-05-05 15:52 UTC, rkuffer approved these changes

2022-05-05 15:55 UTC, rkuffer commented
> ça me semble OK sur le code mais je remarque toujours que lorsque je réduit l'écran, le bouton NEW FAQ disparait et comme il n'y a plus de menu burger cette action n'est pas dispo lors de la réduction d'écran.

Es tu sûr d'être sur la bonne branche ? Le bouton reste affiché quelle que soit la largeur du browser désormais

2022-05-12 11:40 UTC, merged