[DERCBOT-1028] Add Observability Provider to Gen AI Orchestrator
CreditMutuelArkea/tock pull request #364
Opened 2024-06-12 09:18 UTC by assouktim

2024-06-20 13:48 UTC, AurelienSylvan commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/observability/langfuse/langfuse_setting.py
> +        examples=[RawSecretKey(value='sk-lf-93c4f78f-4096-416b-a6e3-ceabe45abe8f')],
C'est une vrai clé valide ?

2024-06-20 13:48 UTC, AurelienSylvan commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/configurations/environment/settings.py
> +    observability_provider_timeout: int = 3
J'imagine que c'est en secondes comme le timeout opensearch. Ce serait bien l'expliciter avec un commentaire.

2024-06-20 13:48 UTC, AurelienSylvan commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/llm/llm_service.py
> +    return await get_llm_factory(query.setting).check_llm_setting(langfuse_callback_handler)
Qu'est ce qui se passe si on appelle `check_llm_settings` avec None ?

2024-06-20 13:48 UTC, AurelienSylvan commented on gen-ai/orchestrator-server/src/main/python/server/tests/services/test_rag_chain.py
> +              'value': 'sk-lf-93c4f78f-4096-416b-a6e3-ceabe45abe8f'
Pareil, c'est pas une clé valide ?

2024-06-24 07:42 UTC, assouktim commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/observability/langfuse/langfuse_setting.py
> +        examples=[RawSecretKey(value='sk-lf-93c4f78f-4096-416b-a6e3-ceabe45abe8f')],
Non c'est du fake

2024-06-24 07:49 UTC, assouktim commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/llm/llm_service.py
> +    return await get_llm_factory(query.setting).check_llm_setting(langfuse_callback_handler)
Je sais pas si tu as regardé la méthode check_llm_setting, tu verras qu'elle a joute pas de handler si c'est None.

2024-06-24 07:49 UTC, assouktim commented on gen-ai/orchestrator-server/src/main/python/server/tests/services/test_rag_chain.py
> +              'value': 'sk-lf-93c4f78f-4096-416b-a6e3-ceabe45abe8f'
non

2024-06-25 16:20 UTC, Benvii requested changes
Great work, it was a bit more complexe to implement that what I had in mind.
They are some "abstraction" issue in the naming of variable that use "langfuse" instead of a more generic naming, I have added comment in each cases.

2024-06-25 16:20 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/langchain_factory.py
> +        trace_name: str) -> Optional[LangfuseCallbackHandler]:
Why not restricting trace_name value to the enum `ObservabilityTrace` ? This way we ensure that all chain respect a strict naming convention enforced by this enum.

2024-06-25 16:20 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +        callback_handlers.append(
Maybe it would be usefull to have a debug log here indicating what kind of observability provider we are creating ?

2024-06-25 16:20 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +            create_langfuse_callback_handler(
This function should clearly be renamed, langfuse is a specific observability provider name : 
```suggestion
            create_observability_callback_handler(
```

2024-06-25 16:20 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/langchain_factory.py
> +def create_langfuse_callback_handler(
Rename it to be generic, langfuse is a specific observability provider name.

```suggestion
def create_observability_callback_handler(
```

Take care to correctly refactor it I may have miss some occurrences.

2024-06-25 16:20 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/completion/completion_service.py
> +            create_langfuse_callback_handler(
```suggestion
            create_observability_callback_handler(
```

2024-06-25 16:20 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/llm/llm_service.py
> +    langfuse_callback_handler = None
```suggestion
    observability_callback_handler = None
```

And refactor the next lines.

2024-06-25 16:20 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/llm/llm_factory.py
> +    async def check_llm_setting(self, langfuse_callback_handler: Optional[LangfuseCallbackHandler] = None) -> bool:
It should use a generic `LangchainCallbackHandler` not a `LangfuseCallbackHandler`

2024-06-25 16:20 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/llm/llm_factory.py
> +            "callbacks": [langfuse_callback_handler] if langfuse_callback_handler else []
rename it to be more generic like `observability_callback_handler` don't mention langfuse

2024-06-26 09:15 UTC, assouktim commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +        callback_handlers.append(
The logs are provided by the factory, which specifies the type of observability provider.

2024-06-26 11:49 UTC, Benvii approved these changes
Ok for me

2024-06-26 11:49 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/configurations/environment/settings.py
> +    observability_proxy_server: Optional[ProxyServerType] = None
Ok for me for the doc in the code.
But maybe we should add on an other ticket a technical documentation with at least on diagram explaining that there is a translation of authentication headers @AurelienSylvan 

Ref : DERCBOT-1085

2024-06-26 11:49 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +        callback_handlers.append(
Ok thanks 👍️

2024-06-26 12:27 UTC, merged