DERCBOT-241 : FAQ existante écrasée si le nom d'intention généré exis…
CreditMutuelArkea/tock pull request #45
Opened 2022-05-17 07:25 UTC by assouktim

…te déjà

2022-05-17 08:25 UTC, brandonsechet commented on bot/admin/web/src/app/faq/faq-definition/faq-definition.component.ts
> +import {map, take, takeUntil} from "rxjs/operators";
map et take ne sont pas utilisés, à supprimer

2022-05-17 08:25 UTC, brandonsechet approved these changes

2022-05-17 08:37 UTC, rkuffer approved these changes

2022-05-17 08:37 UTC, rkuffer commented on bot/admin/web/src/app/faq/faq-definition/faq-definition.component.ts
> +import {map, take, takeUntil} from "rxjs/operators";
Un détail sans conséquences mais il me semble que les deux opérateurs ajoutés ne sont pas utilisés

2022-05-17 15:01 UTC, davhamelin requested changes
Il y a un petit problème de couverture de test.
Les TU mock l'appel à "createOrUpdateIntent" et donc il n'y a aucun test du code modifier.
ça serait pas mal d'ajouter 2-3 tests qui ne mock pas cette méthode (mais qui mock quand même les accès BDD, ça va sans dire).

2022-05-17 16:04 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +    private fun findFaqDefinitionIntent(faqId : Id<FaqDefinition>) : IntentDefinition? {
et je viens de remarqué qu'il y a le même problème sur "faqId : Id<..." il y a aussi un espace de trop

2022-05-18 09:16 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +        return intentDAO.getIntentById(faq!!.intentId)
[info]
idem pour le "Id<FaqDefinition>) : IntentDefinition" qui devrait être "Id<FaqDefinition>): IntentDefinition"

2022-05-19 07:53 UTC, assouktim commented on bot/admin/web/src/app/faq/faq-definition/faq-definition.component.ts
> +import {map, take, takeUntil} from "rxjs/operators";
Oui

2022-05-19 07:56 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +            this.findFaqDefinitionIntent(query.id.toId())!!.name
Ca marche

2022-05-19 09:17 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +    private fun getIntentName(query: FaqDefinitionRequest,) : String {
je viens de cheker la doc, effectivement il font bien bien cette différence en écriture. Ok c'est noté

2022-05-19 10:36 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +            query.intentName!!
Oui, car le front envoi déjà le name formaté

2022-05-19 10:37 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +            this.findFaqDefinitionIntent(query.id.toId())!!.name
ok je vois. je vais le gérer au dessus

2022-05-19 10:38 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +        return intentDAO.getIntentById(faq!!.intentId)
idem

2022-05-30 13:07 UTC, davhamelin approved these changes

2022-06-07 08:58 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +        val name: String = requireNotNull(this.getIntentName(query)) { "Intent name is missing !" }
ok c'est noté et bien pris en compte

2022-06-07 10:57 UTC, davhamelin approved these changes

2022-06-14 08:42 UTC, merged