FAQ Settings
CreditMutuelArkea/tock pull request #55
Opened 2022-06-14 13:57 UTC by assouktim

2022-06-15 08:51 UTC, djowalker requested changes
Des améliorations à voir

2022-06-15 08:51 UTC, djowalker commented on nlp/front/shared/src/main/kotlin/config/FaqSettings.kt
> + * Copyright (C) 2017/2021 e-voyageurs technologies
2022

2022-06-15 08:51 UTC, djowalker commented on nlp/front/shared/src/main/kotlin/config/FaqSettingsQuery.kt
> + * Copyright (C) 2017/2021 e-voyageurs technologies
2022

2022-06-15 08:51 UTC, djowalker commented on nlp/front/shared/src/main/kotlin/config/FaqSettingsQuery.kt
> +class Settings(
ça devrait se nommer FaqSettingsQuery plutôt non ?

2022-06-15 08:51 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceSettingsTest.kt
> + * Copyright (C) 2017/2021 e-voyageurs technologies
2022

2022-06-15 08:51 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +        val faqSettings = faqSettingsDAO.getFaqSettingsByApplicationId(application._id)?.toSettings()
toFaqSettingsQuery() donc ?

2022-06-15 08:51 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +        return faqSettingsDAO.getFaqSettingsByApplicationId(applicationDefinition._id)?.toSettings()
toFaqSettingsQuery donc ?

2022-06-15 08:51 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +    fun saveSettings(applicationDefinition: ApplicationDefinition, settings: Settings): Settings {
Type de retour FaqSettingsQuery ?

2022-06-15 08:51 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +        val features = mutableListOf<StoryDefinitionConfigurationFeature>()
Peut-être à décaler ce qui concerne les features dans une méthode privée dans ce cas ?

2022-06-15 08:51 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceSettingsTest.kt
> +            satisfactionStoryId = null,
Pourquoi null ?

2022-06-15 08:51 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +        val faqSettingsUpdated = (
Rajouter des commentaires sur le duplicat de données ?

2022-06-16 07:33 UTC, assouktim commented on bot/admin/server/src/test/kotlin/FaqAdminServiceSettingsTest.kt
> +            satisfactionStoryId = null,
la storyId est à null lorsque la satisfaction est désactivée

2022-06-17 12:48 UTC, djowalker reviewed
Me semble qu'il manque également le commentaire concerant la duplication de donnée.

2022-06-17 12:48 UTC, djowalker commented on nlp/front/shared/src/main/kotlin/config/FaqSettings.kt
> +    fun toSettings(): FaqSettingsQuery{
toFaqSettingsQuery donc?

2022-06-23 12:43 UTC, djowalker approved these changes

2022-06-24 10:44 UTC, djowalker approved these changes

2022-06-29 17:08 UTC, closed without merging