Dialog Manager - DERCEBOT 214-268-269-270-278
CreditMutuelArkea/tock pull request #82
Opened 2022-08-09 07:35 UTC by assouktim

2022-08-10 16:04 UTC, davhamelin requested changes
Il y a énormément de code, je suis peut être passé à coté de certaines choses.

2022-08-10 16:04 UTC, davhamelin commented on bot/engine/src/main/kotlin/engine/dialog/Dialog.kt
> +                tickStates = dialog.tickStates
j'ai l'impression que ce comportement est un peu trop spécifique au dev qui est fait ici. d'un point de vu expérimental, je comprend l'idée, mais un dialog est un objet générique. 
si on commence à avoir des éléments vide qui ne sont remplie que lorsqu'on utilise tock d'une certaine manière, ça risque de fortement nuire à la maintenabilité du code.
Je n'ai pas de solution alternative à proposer à la place, il faudrait y réfléchir.

2022-08-10 16:04 UTC, davhamelin commented on bot/storage-mongo/src/main/kotlin/collections/DialogCol.kt
> +                tickStates = this.tickStates.toMutableMap()
pour l'ensemble du fichier DialogCol : même remarque quand au fait de modifier l'objet Dialog de cette manière.

2022-09-06 12:04 UTC, assouktim commented on bot/admin/server/src/main/kotlin/BotAdminService.kt
> +        // TODO MASS : RG existantes, quel est l'attendu pour la tickstory ?
Oui une JIRA sera rédigée pour gérer ce cas.

2022-09-06 12:14 UTC, assouktim commented on bot/admin/server/src/main/kotlin/BotAdminService.kt
> +        botConf ?: return
C'est le comportement existant l'hors de l'enregistrement d'une story, pas de changement sur la règle si pas de botConfiguration trouvé, l'enregistrement n'est pas effectué.
J'ai modifié en ajoutant une badRequest si pas de botConf.

2022-09-06 12:16 UTC, assouktim commented on bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
> +        if(applicationDefinition == null || context.organization != applicationDefinition.namespace) {
ok

2022-09-06 12:17 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
> +    // TODO : impact the frontend to use TickConfiguration
non c'est un résidu

2022-09-06 12:18 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
> +    fun validateTickStory(): List<String> {
Oui dacc

2022-09-06 12:18 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
> +            .forEach { errors.add("Intent $it not found in StateMachine") }
oui ok

2022-09-06 12:56 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
> +        }
oui les deux validations sont indispensables, il faut checker les inputs par rapport aux outputs et inversement. 
la validation se fait à l'enregistrement qui, elle même, se fait à la dernière phase de production du scénario, à ce stade tout doit être développé et finalisé.

2022-09-06 13:00 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
> +            run {
je me rappel plus, je pense que j'ai utilisé le run car j'avais des prob de visibilité (scope) des variables au sein des différents bloc, j'aurai pas du faire ça. Oui ça compile, je l'ai retiré

2022-09-06 13:00 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
> +            run {
idem

2022-09-06 13:54 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
> +        return errors.toList()
je comprends bien la méthodologie, j'ai retravaillé l'algo pour le simplifier car au final le contrôle sur les contextes corresponds à faire une intersection des deux listes (input par rapport à l'output, et inversement).

2022-09-06 13:59 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/processor/Stack.kt
> +class Stack<T> {
C'est un grave oubli :), j'ai rectifié

2022-09-06 14:06 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +            when(val nextStateId = currentState.on?.get(transition)){
le 'on' est un mot cle de la xState.

2022-09-06 14:07 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +class StateMachine(val root: State) {
C'est ça que j'ai pris en compte

2022-09-06 14:09 UTC, assouktim commented on bot/dialog-manager/src/test/kotlin/ai/tock/bot/handler/provider/joignabilite/TickStoryJoignabilitePlafondsVirementTest.kt
> +class TickStoryJoignabilitePlafondsVirementTest {
oui, j'ai ajoutai un TODO

2022-09-06 14:09 UTC, assouktim commented on bot/dialog-manager/src/test/kotlin/ai/tock/bot/processor/StackTest.kt
> +class StackTest {
Fichier supprimé

2022-09-06 14:56 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +        when(stateMachine.id){
Je ne vois pas pk il faut éviter d'utiliser les switch. Je n'ai pas vu dans la doc qlq chose qui fait une telle recommandation. Je préfère écrire des When à la place d'un if/else, je trouve ça beaucoup plus propre, plus concis et lisible.
Normalement le compilateur convertit le when en if/else si c'est binaire, et en switch s'il y a plus de deux options.

2022-09-06 15:22 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +    private fun getInitial(id: String, stateMachine: State): State? {
j'ai ajouté un commentaire

2022-09-06 15:23 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +        when(stateMachine.states?.any { entry -> entry.value.id == id }){
nop

2022-09-06 15:25 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +                else -> getInitial(nextStateId.drop(1), stateMachine)
Structure des données Xstate : 
...
"on": {
            "i_preciser_montant": "#RESOLVE",
            "lEtranger": "#RESOLVE",
            "laFrance": "#RESOLVE"
          },
...

le drop est pour supprimer le #
j'ai ajouter un commentaire

2022-09-06 15:29 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +        }
Le check de la boucle infinie a été ajouté à instanciation de la state machine

2022-09-06 15:29 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +    private fun containsTransition(transition: String, stateMachine: State): Boolean =
Le check de la boucle infinie a été ajouté à instanciation de la state machine

2022-09-06 15:29 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +            else -> stateMachine.states?.firstNotNullOfOrNull { getParent(id, it.value) }
Le check de la boucle infinie a été ajouté à instanciation de la state machine

2022-09-06 15:30 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +            else -> stateMachine.states?.firstNotNullOfOrNull { getState(id, it.value) }
Le check de la boucle infinie a été ajouté à instanciation de la state machine

2022-09-06 16:15 UTC, davhamelin commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +        when(stateMachine.id){
https://rules.sonarsource.com/java/RSPEC-1301?search=switch

2022-09-06 16:19 UTC, davhamelin commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +        when(stateMachine.id){
ce n'est pas une recommandation kotlin, ou java, je l'ai lu dans "clean code", exemple à l'appuis.
Normalement un switch à pour but de distinguer plusieurs cas, or dans ce cas précis, tu distingue un seul cas. Tu a un cas, et un contournement si aucun de tes 1 cas n'est pas reconnu. C'est extrêmement perturbant à lire. La première fois que j'ai lu ce bout de code, j'ai pensé qu'il manquait quelques chose entre le id-> ... et le else ->
Le block de code du else fait beaucoup de chose, un accesseur sur une liste, un test non null, un mapper avec appel d'une méthode récurcive, un filter not null. Toute la partie du else devrait être dans une méthode genre 
`else -> retrieveState(stateMachine)`
Mais ça rendrait très compliqué la lecture de la récurcivité.

En général, un switch sert à faire genre "lorsque [variable], premier cas : A, deuxième cas : B, troisième cas : C,... sinon erreur cas de variable non traité". Et dans ce cas là, il est recommander de préférer le polymorphisme, et une factory (si c'est possible). ça donne du code complexe mais simple à maintenir, et avec la possibilité d'ajouter des cas sans trop de difficulté, et sans oublier de "case" (a ajouter manuellement dans un ou plusieurs switch). (Sometimes it’s worth to use polymorphism rather than a switch. Using switch often breaks the SRP (more than one reason to change) and OCP (must change whenver new types are added), and sometimes even causes duplicating the same switch costructions in several functions. Instead create classes for each switch case, and bury the switch itself deep in an Abstract Factory. https://monikma.github.io/2016/01/13/clean-code-robert-c-martin-notes.html)  (https://blog.cleancoder.com/uncle-bob/2021/03/06/ifElseSwitch.html)
Mais dans le cas présent ce n'est pas applicable. Ici tu es vraiment dans le cas d'un "si j'ai trouvé l'élément que je cherche, je m'arrête; sinon si je n'ai pas atteins la condition de sortie de la récursion, je lance une récursion; sinon je sort en informant que je n'ai pas trouvé"

Autre problème, si tu veux ajouter la condition de sortie qui n'est pas lier à stateMachine.id, ça donnerais quelques chose de pas terrible.
```
 when(stateMachine.id){
            id -> stateMachine
            else -> {
                   if([condition de sortie non résolu]) {
                    [ récursion ]
                  } else { //condition de sortie
                    null
                  }
             }
}
```

 avec un if c'est plus simple :
```
if(stateMachine.id == id) {
 stateMachine
} else if([condition de sortie non résolu]) {
  [ récursion ]
} else { //condition de sortie
  null
}
```

Avant je pensais comme toi, j'aimais bien, et je préférais faire des switch case dans certains cas. En fait, à partir du moment où une méthode à besoin d'un switch cas, c'est qu'il y a un problème quelques part, car alors, la méthode fait plein de chose différentes qui dépendent d'un test.

2022-09-06 16:39 UTC, davhamelin commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +            else -> getInitial(state?.initial!!, state)
si le state n'a pas d'initial ?

2022-09-06 17:15 UTC, davhamelin commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +        return when(state?.states?.isEmpty()){
ici c'est encore plus problématique, et encore moins lisible que dans le cas précédent d'utilisation du when.
Il y a un test dans le when ... le isEmpty().
tu à changer un "if(boolean) { action } else { autre action } " en 
```
switch(boolean) { 
    case true;
    case null: 
        action commune au true et null
        break
    default : 
        autre chose
}
```
(ce qui reviens à faire if(boolean == true || boolean == null ) { action } else { autre action } )

le cas présent pourrait même être écrit en ternaire 
`return state?.states?.let { getInitial(state!!.initial!!, state) } ?: state`
(on est sur que le initial de state ne peut pas être null ici ? un commentaire pour expliqué pourquoi peut être ?)
Je dis pas que mon ternaire est plus lisible.

```
if(state.containsStates() && state.haveInitial()) {
   getInitial(state!!.initial!!, state)
} else {
   state
}

fun State?.containsStates() = this?.states?.isNotEmpty() ?: false

//j'ai pas tout relu pour voir si il y a besoin de check le initial avant de forcé le !!
fun State?.haveInitial() = (this?.initial != null) ?: false

```
là t'a un if, avec plusieurs conditions à remplir, lorsque toute les conditions sont remplie (condition qui sont lisible par un humain), alors tu exécute le bloque de code. sinon tu retourne autre chose. La seul chose à ajouter c'est un peu de commentaire. par exemple pour le else "si il n'y a pas de sous states, ou pas d'initial, alors le state courant est le celui recherché"

Si j'essais de lire en langage naturel ce que tu a écris : 
"quand state lorsqu'il existe a ses states vide. Dans le cas où null ou vrai alors répondre state. Dans tout les autres cas, lancer une récursion sur state et l'initial de state qui n'est certainement pas null"

Si je lis l'écriture avec un if :
"Si state contient des states, et state a un initial. Alors lancer la récursion sur state et l'initial de state. Sinon retourner state"

Ce n'est pas parce que le code est plus concis, qu'il est plus lisible.

2022-09-08 12:51 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +        when(stateMachine.id){
Le sonar que tu mentionnes ici est pour le Java. En Kotlin, sonar n'a pas fait de recommandation pour le nombre de branche qu'un when statement doit à minima gérer. Comme j'ai dit, le compilateur Kotlin convertit le when en if/else si c'est binaire, et en switch s'il y a plus de deux options, donc ça ne pose pas de prob. En terme de lecture de code, je trouve ça claire et sans d’ambiguïté. 
L'exemple que tu mentionnes sur l'ajout d'une condition de sortie qui n'est pas lié à stateMachine.id, si c'est le cas, j'aurai pas utiliser when. Imbriquer en profondeur le code dans plusieurs blocs (when ou if) n'a jamais été quelque chose de bien.
Dernière chose, ce n'est pas l'existante d'un When ou d'un if/else qui fait que la méthode fait plein de chose différentes, c'est le nombre de branches, ainsi que la nature du traitement/instruction écrit dans chaque branche qui laisse penser à ça.

2022-09-08 13:06 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +            else -> getInitial(state?.initial!!, state)
Le state dans ce cas est un "group". Un group à toujours à initial (RG Xstate)

2022-09-08 14:37 UTC, assouktim commented on bot/engine/src/main/kotlin/engine/config/ConfiguredStoryHandler.kt
> +    }
méthode supprimée car non utilisée, mais l'idée est utilisée dans le bon endroit

2022-09-09 09:42 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/processor/TickStoryProcessor.kt
> +                when(objectivesStack.isEmpty()) {
le when est aussi approprié :)

2022-09-12 12:58 UTC, assouktim commented on bot/dialog-manager/src/test/kotlin/ai/tock/bot/statemachine/StateMachineTest.kt
> +class StateMachineTest {
Le cas d'id non présent était bien présent. J'ai ajouté celui de la boucle infini. Y a pas de problème à les faire en fichier json.

2022-09-13 14:38 UTC, assouktim commented on bot/engine/src/main/kotlin/engine/dialog/Dialog.kt
> +    val tickStates: MutableMap<String, TickState> = mutableMapOf()
J'ai un laissé un TODO avec tes commentaires pour les traiter ultérieurement car c'est un sujet à creuser davantage. La priorité est de merger le code en l'état pour pouvoir faire les autres tickets. Nous reviendrons sur ces TODO après.

2022-09-13 14:39 UTC, assouktim commented on bot/engine/src/main/kotlin/engine/dialog/Dialog.kt
> +                tickStates = dialog.tickStates
idem

2022-09-13 14:39 UTC, assouktim commented on bot/storage-mongo/src/main/kotlin/collections/DialogCol.kt
> +                tickStates = this.tickStates.toMutableMap()
idem

2022-09-13 15:07 UTC, assouktim commented on bot/dialog-manager/src/main/kotlin/ai/tock/bot/statemachine/StateMachine.kt
> +        return when(state?.states?.isEmpty()){
Le test dans le when dont tu parles, tu l'a mis dans la fonction  containsStates en utilisant un ternaire ! si ça est lisible je vois pas pk ça te gènes ce qui mis dans le when. Sorry David, je ne suis vraiment pas convaincu, je ne vois pas ce qui est pas normal dans l'expression state?.states?.isEmpty() c'est une instruction tout a fait lisible. 
En français, mon code dit : si l'etat n'est pas un groupe, alors envoyer cet etat, sinon continuer la recherche dans cet etat en utilisant son initial obligatoirement présent.

2022-10-06 07:12 UTC, assouktim commented
Cette PR est fermée car une nouvelle review sera réalisée au moment du merge sur la contrib.

2022-10-06 07:12 UTC, closed without merging