dercbot 253 : FAQ title
CreditMutuelArkea/tock pull request #85
Opened 2022-08-12 14:53 UTC by assouktim

2022-09-06 14:30 UTC, djowalker requested changes
Des améliorations possibles et challenger @jygdev sur les sujets de la description de l'intention / story.

2022-09-06 14:30 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +    fun searchFAQ(query: FaqSearchRequest, applicationDefinition: ApplicationDefinition, botId: String): FaqDefinitionSearchResult {
botId= applicationDefinition.name non ?
Pas besoin de rajouter ce paramètre je pense.

2022-09-06 14:30 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +        val faqStories = BotAdminService.findConfiguredStoriesByBotIdAndIntent(namespace, botId, intentNames)
Meilleure JavaDoc de méthode avec les paramètres ?
Eventuellement un commentaire applicationDefintion= botId dans ce cas ?

2022-09-06 14:30 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> +            val faqResult = faqAdminService.searchFAQ(faqSearchRequest, applicationDefinition, botId)
Plus besoin de botId d'après ce qui a été énoncé plus haut.

2022-09-06 14:30 UTC, djowalker commented on nlp/front/shared/src/main/kotlin/config/FaqDefinitionDetailed.kt
> +    val faq: IntentDefinition, // TODO MASS : do not update intent name/label, update story name
TODO à enlever

2022-09-06 15:07 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +            findFaqDefinitionIntent(query.id.toId())
Réponse de @jygdev : 
On ne met à jour que la Story, on ne touche pas à l'intention,
On ne la touche plus une fois créée car si on utilise une intention partagée on va impacter les autres bots qui utilisent cette intention.
La story n'étant pas partagée on peut modifier la description et le libellé comme on veut.

Donc le createOrUpdateIntent, ne devrait plus que s'appeler `createIntent` et donc enlever tout son processus de mise à jour si besoin. Avec quelques commentaires d'explications :)

2022-09-06 15:08 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> +        // TODO MASS : Voir avec JY: MAJ Jira, l'intention ne doit pas etre MAJ, seule la faq + label de la story
Il faut màj la description de la story.

2022-09-06 15:13 UTC, djowalker reviewed
Des infos supplémentaires et corrections à faire concernant les retours de JY.

2022-09-07 09:08 UTC, assouktim commented on bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
> +                        FaqAdminService.searchFAQ(request, applicationDefinition, botConf[0].botId)
Oui le botId = applicationDefintion.name
Je corrige mon code

2022-09-07 17:11 UTC, djowalker requested changes
Des petites améliorations mais c'est plutôt bon.

2022-09-07 17:11 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> +                applications = setOf("appId-$intentId".toId()),
il manque la category si on veut être propre au fait que ça soit une FAQ?
cf : createFaqQueryResult(...)

createIntent = (...)
category = FAQ_CATEGORY.

Après il ne me semble pas qu'on y touche après puisqu'elle est créée qu'une seule fois.

2022-09-07 17:11 UTC, djowalker commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> +                verify(exactly = 0) { faqAdminService["getIntentName"](any<FaqDefinitionRequest>()) }
je pense qu'il serait juste judicieux de renommer existingFaqQuery avec une information dans le nom de la variable comme quoi l'intentName est null.

2022-09-07 17:13 UTC, djowalker commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +    fun searchFAQ(query: FaqSearchRequest, applicationDefinition: ApplicationDefinition, botId: String): FaqDefinitionSearchResult {
Le pouce vers le bas c'est pour montrer que tu n'es pas d'accord et que tu avais vu autre chose ou missclick ?^^

2022-09-08 07:45 UTC, assouktim commented on bot/admin/server/src/main/kotlin/FaqAdminService.kt
> +    fun searchFAQ(query: FaqSearchRequest, applicationDefinition: ApplicationDefinition, botId: String): FaqDefinitionSearchResult {
Oops! c'est vers le haut que je voulais mettre ;)

2022-09-08 08:25 UTC, assouktim commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> +                applications = setOf("appId-$intentId".toId()),
Oui la catégorie de la story n'a pas d'importance dans ce test, il n'est pas utilisé à aucun moment, mais je la mettrai pour avoir un jeux de donnée plus réaliste.

2022-09-08 08:45 UTC, assouktim commented on bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
> +                verify(exactly = 0) { faqAdminService["getIntentName"](any<FaqDefinitionRequest>()) }
Oui ce TU et d'autres ne sont plus correcte. Normalement l'intentName est obligatoire, elle est bien fournie à la création et à l'update. Je vais changer le fait qu'elle est optionnelle, et je ferai la MAJ des TU. Que penses-tu ?

2022-09-08 14:58 UTC, djowalker approved these changes

2022-09-08 15:02 UTC, djowalker commented on bot/admin/server/src/main/kotlin/model/FaqDefinitionRequest.kt
> +    var title: String,
cf le dernier commit.

2022-09-15 09:37 UTC, merged