Feature/scenarios/dercbot 287
CreditMutuelArkea/tock pull request #96
Opened 2022-09-01 08:11 UTC by davhamelin

ajout de la gestion d'historique coté back

2022-09-06 17:27 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioExceptionManager.kt
> +            throw when(scenarioException) {
ce when ne me convient pas, mais je n'ai pas trouver d'autre solution.
J'aurais préféré pouvoir faire de l'injection d'interface sur les ScenarioException pour ajouter la méthode toRestException(), puis injection de surcharge de méthode pour ajouter individuellement les implémentations concrète. Ensuite je n'aurais eu qu'a faire un scenarioException.toRestException() et par polymorphisme, la méthode toRestException() se serait résolut sur la bonne classe.
Je m'attendais à ce que de cette manière, la classe ScenarioExceptionManager ne compile pas, tant que certaines implémentation de ScenarioException n'aurait pas reçu leurs surcharges.
Mais ce n'est pas possible, pour l'instant en kotlin on ne peut pas injecter une interface.
J'ai choisi d'utiliser un when, qui, bien qu'il semble être très redondant, produit un safe cast de scenarioException en la classe concrété testé pour appeler la bonne méthode toRestException() injecté.

2022-09-06 17:31 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioExceptionManager.kt
> +            throw when(scenarioException) {
Si nécessaire, je peux sortir le when dans une méthode qui prend en paramètre une ScenarioException, et retourne une restException. De telle sorte que le when soit dans une méthode qui ne contient que le when (ce qui est une bonne pratique)

2022-09-07 16:08 UTC, djowalker requested changes
Code de bonne manufacture.
Pas mal de petites erreurs en anglais et pas mal de propositions de formulation.

Je crois que j'ai qu'une ou deux questions dans le lot mais ça semble OK.

2022-09-07 16:08 UTC, djowalker commented on bot/engine/src/main/kotlin/admin/scenario/Scenario.kt
> +    val versions: List<ScenarioVersion> = emptyList(),
En relisant la partie DAO, c'est vrai que ça paraît pertinent en terme de représentation par document

2022-09-07 16:08 UTC, djowalker commented on bot/engine/src/main/kotlin/admin/scenario/ScenarioVersion.kt
> +    val name: String, //must be moved in Scenario ?
En relisant la partie DAO, personnellement je trouve ça cohérent en représentation documentaire dans la base. Je ne sais pas cela était à discuter pour toi ?

2022-09-08 14:58 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioExceptionManager.kt
> +            //TockException use a non-null message,
c'était voulu, j'avais fait un bloque de 3 lignes, dont la première était décalé d'un espace ... mais dans le fond, c'est vrai que ça sert à rien et ça perturbe plus la lecture qu'autre chose. donc je supprime.

2022-09-08 16:11 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioPredicate.kt
> +            //check versions to update don't contain version not already in database in the scenario
"check that versions to update don't contains version not in database"
Tout aussi simple.
En gros, dans la map, il faut que toutes les versions soient connu en BDD. ou dit dans l'autre sens, il faut vérifier que dans la liste des scénarios à mettre à jours, il n'y en ai aucun qui ne soit pas en bdd.

2022-09-08 16:33 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioPredicate.kt
> +                with(it) {
si, ça donnerais : 

            versions.forEach { scenarioVersion ->
                with(scenarioVersion) {...}

ou plus sobre 
            versions.forEach { element ->
                with(element) {...}

Il vaut mieux éviter d'utiliser le mot "version" sinon ça serait confusant entre le nom de la ScenarioVersion et la variable version dans ScenarioVersion (en gros ça serait version.version, masqué par le with)

Utiliser un scenarioVersion me gène (je n'utilise nul part ailleurs de variable "scenarioVersion" pour désigner une version), et le mot "element" est a peine mieux que "it" .

C'est une fonction que je n'aimep as beaucoup, mais il faut aussi reconnaitre, qu'avec intellij, la manière dont ça s'affiche c'est : 
versions.forEach { it: ScenarioVersion
   with(it) { this: ScenarioVersion
(avec les it et this: grisé)

2022-09-08 16:43 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioPredicate.kt
> +            forEach {
ok, mais je pense qu'il faut quand même y allez avec parcimonie. La précédente méthode où j'ai utilisé un with, j'avais 9 variable préfixé d'un it, et plusieurs ligne avec plusieurs "." genre "it.version.isMachin()" ou "variable.contains(it.version)" ce qui ne facilite pas la lecture.
Là il n'y a que 5 variable dont le it représente le seul "." (que des accesseurs). 
Par contre c'est vrai que ça améliore le formatage de la string, on passe d'un "du texte ${it.variable} du text" à "du text $variable du text" et c'est mieux.

2022-09-08 16:43 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioPredicate.kt
> +         * else, return scenario
ouais, j'en ai mis partout, c'est mieux

2022-09-08 17:14 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioServiceImpl.kt
> +    private fun findVersionsByIdIfExist(id: String?): List<ScenarioVersion> {
alors non ... on ne cherche pas les version qui existe, on cherche à trouver les version si l'id passé en paramètre existe (puis qu'il a le droit d'être null).
avec findExistingVersionsById c'est les versions qui sont "existing" non ?

Le mieux serait peut être de juste viré le ifExist 
findVersionsById

normalement le findById retourne un scenario, mais comme là on retour des versions, ça le fait. La seul différence c'est qu'un findById produit un notfound si on ne trouve rien, alors que là on produit une liste vide, c'est la raison pour laquelle je voulais marqué la différence de comportement par le ifExist, mais ça peut aussi etre un : 
findVersionsByIdOrEmpty ?

2022-09-08 17:16 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioServiceImpl.kt
> +            // remove existing version in database before return
ouais, en fait, on les "retire/enlève de la liste qu'on va retourné" (j'aurais utilisé le mot "delete" pour dire supprimer).
On peu reformuler le commentaire avec "exclude existing ..." si c'est plus claire

2022-09-08 17:17 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioServiceImpl.kt
> +            // remove existing version in database before return
même réponse que précédemment.

2022-09-08 17:23 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioServiceImpl.kt
> +    private fun Scenario.changeDateToCreate(): Scenario {
alors non, il s'agit de "mettre à jours LES dates POUR la création"
on ne fait pas que mettre à jours la date de création à la date courante, on écrase aussi la date d'update à "null" (c'est volontaire).
le mot "update" devient perturbant surtout avec l'update : "updateDatesUpdate" ou "updateDatesToUpdate"

avec un changeDatesToCreate (je viens de rajouter un s à dates du coup) ça fait ce que ça dit : ça change les date pour la création (en bdd) de l'objet

on peut faire un changeDatesToCreateInDataBase (et la même pour update), mais je trouve que ça commence à être un peu à ralonge, et puis ... qu'on créé en base, ou ailleurs, dans le fond, je n'ai fait qu'appliqué la règle métier transformation des dates à réalisé lors de la création. Cette méthode ne sais pas à quoi servira l'objet modifier, et n'aura aucun controle dessus en bdd, donc pas besoin de le préciser.

2022-09-08 17:28 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioServiceImpl.kt
> +        return versions.filter(haveVersion).associateBy( { it.version!! }, { it.createDate })
la variable s'appel "createDate" 
la méthode "extrait les 'createDate' et les organises dans une map par version"
la partie "createDateByVersion" c'est plus un nommage classique pour dire "ça produire une map de 'truc de gauche' organisé par 'truc de droite' comme clé"
Si on avait été en java, j'aurais probablement fait un getCreateDateByVersion()

on peut même replacé par createDateByVersion mais ça produit une embiguité je trouve, on pourrait pensé que ça "créer des date (lesquelles?) par version"
Je te laisse me dire ce que t'en pense.

2022-09-09 15:37 UTC, davhamelin commented on bot/admin/server/src/main/kotlin/scenario/ScenarioVerticle.kt
> +        //return
comme on est sur des lambda, on a pas trop le choix, on ne peut pas faire de return explicite, ce qui est retourné dans une lambda, c'est la dernière variable à avoir été traité, c'est vraiment pas ouf, du coup je rajoute une return pour explicité ce qui est retourné mais là il est mal placé à cause du exceptionmanager.catch, je vais le baisser d'un cran

2022-09-09 15:53 UTC, davhamelin commented on bot/engine/src/main/kotlin/admin/scenario/ScenarioVersion.kt
> +    val name: String, //must be moved in Scenario ?
Si je déplace ces éléments dans scénario, voila ce qui va se passer (pour reprendre un gimmick du visiteur du futur, actuellement en salle de cinémas !) :
Si on a 2 versions pour un scénario (autrement dit, du point de vu front : 2 scenario pour le même sagaID)
qu'ils modifient la première version en changeant (par exemple) le name pour : "Marcus1"
puis qu'il modifie la deuxième version en changeant le name pour : "Marcus2" 
on aura 2 versions avec 2 nom différent, et ça ne sera pas un problème, la première sera Marcus1 et la deuxième Marcus2.
Mais si on déplace le name au niveau de scénario, après la modification de la version 2, le name de la version 1 sera aussi Marcus2. ça me parrait ne pas avoir de sens, ne pas être logique. Mais comme je ne comprend pas ce que veux le front et comment ils manipules les données, et que ça n'a pas été décrit fonctionnellement, je ne peux pas me permettre d'imposer ce choix.
Il faudrait que ça soit clairement acté que, ce qui change entre 2 version d'un scénario, c'est le state, les date, et la data, et que tout le reste est commun à un sagaId et que si il y a un changement, il se répercute forcément sur toutes les versions, et qu'ainsi on a pas besoin de versionner le nom, la description, les tag, etc. Il faudrait qu'on sache clairement ce qui est versionner ou non, pour pouvoir déplacer certain des élements que j'ai commenté en //must be moved ... 
Comme je ne serais plus là quand la question se posera, je laisse cette tache à mon successeur.

2022-09-09 15:53 UTC, davhamelin commented on bot/engine/src/main/kotlin/admin/scenario/ScenarioVersion.kt
> +    val name: String, //must be moved in Scenario ?
du coup j'ai rajouté un commentaire : 


 * There was no functional reflection on what should be versioned and what should not be.
 * As a result, everything has been versioned to be able to provide coherent responses
 * to the front in relation to their requests.
 * It seems important to me to take the time to rethink the problem so as not to version everything.
 * Some elements such as the name, or the description, or the applicationID for example,
 * are common to all versions of the same scenario and should therefore be saved in the parent object (Scenario).
 * All variables that appear moveable have a //must be moved comment.
 * Think about it.

2022-09-09 15:55 UTC, davhamelin commented on bot/admin/server/src/test/kotlin/scenario/ScenarioMapperTest.kt
> +        assertDoesNotThrow { ScenarioMapper() }
oui, juste pour couvrir le constructeur, vide ou non.

2022-09-09 17:16 UTC, davhamelin commented on bot/engine/src/main/kotlin/admin/scenario/Scenario.kt
> +    val versions: List<ScenarioVersion> = emptyList(),
ça reste en suspend comme expliqué dans le commentaire en lien avec le ScenarioVersion (j'ai ajouté du commentaire dans le code)

2022-09-09 17:22 UTC, davhamelin commented on bot/storage-mongo/src/main/kotlin/ScenarioMongoDAO.kt
> +     */
la subtilité, c'est que je rajoute des @throws 
comme se sont des exceptions runtime, elles n'ont pas à être déclaré dans l'interface (elles pourraient ne pas existé) mais pour qu'on sache quel exception l'implémentation que j'ai fait peuvent produire, j'ai remis le com en ajoutant les exceptions (et je l'ai fait aussi pour les méthodes qui ne throw pas ... pour plus d'uniformité)

2022-09-09 17:26 UTC, davhamelin commented on bot/storage-mongo/src/main/kotlin/ScenarioMongoDAO.kt
> +            .aggregate<ScenarioCol>(match(Filters.eq("versions.version", version)))
effectivement. je m'y attellerais lundi, je te poserais peut être des questions à ce moment là.

2022-09-09 17:31 UTC, davhamelin commented on bot/storage-mongo/src/main/kotlin/collections/ScenarioCol.kt
> +    var versions: List<ScenarioVersionCol>
pas sur de comprendre le commentaire. qu'entends tu par "revoir ça dans les DTO" ?

2022-09-12 16:06 UTC, davhamelin commented
> Code de bonne manufacture. Pas mal de petites erreurs en anglais et pas mal de propositions de formulation.
> 
> Je crois que j'ai qu'une ou deux questions dans le lot mais ça semble OK.

prise en compte des différentes remarques

2022-09-12 16:07 UTC, davhamelin commented
> Code de bonne manufacture. Pas mal de petites erreurs en anglais et pas mal de propositions de formulation.
> 
> Je crois que j'ai qu'une ou deux questions dans le lot mais ça semble OK.

Je ne peux pas merge, il y a peut être quelques chose à faire de ton coté ?

2022-09-13 10:31 UTC, djowalker requested changes
Petites fautes d'orthographes qui persistent

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/src/test/kotlin/scenario/ScenarioVerticleTest.kt
> +    fun `getAllScenarios WHEN findAll returns a list of valide scenario THEN returns a list of ScenarioResult`() {
of valid*

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/src/main/kotlin/scenario/ScenarioServiceImpl.kt
> +     * Delete an existing scenario with all this version
with all its versions ? On supprime un scénario et toutes ses versions ?

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/src/main/kotlin/scenario/ScenarioPredicate.kt
> +         * Throws exception if scenarios ids are différent
different pas différent*

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/src/main/kotlin/scenario/ScenarioMapper.kt
> +         * Create new scenario with versions that contain histories of original and histories passed in parameter
that contains

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/src/main/kotlin/scenario/ScenarioMapper.kt
> +         * Create new scenario with versions that contain histories of original excluded from those passed in parameters
that contains

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/src/main/kotlin/scenario/ScenarioMapper.kt
> +         * Create new collection of scenarios with versions that contain no archived version
that contains

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/src/main/kotlin/scenario/ScenarioExceptionManager.kt
> + * Copyright (C) 2017/2021 e-voyageurs technologies
2022 ?

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +La date de création est initialisée à la date courante du serveur, la date de mise à jour est initialisé à null.<br>
la date de mise à jour est initialisée

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +_Erreur 409_ : l'une des versions à créer à un id.<br>
a un id

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +_Erreur 500_ : il y a plus d'une version retourné.<br>
retournée

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +Si un id de scénario est renseigné dans le body, le service trouve le scénario, et en extrait les versions. Les versions existantes sont ajoutés aux nouvelles versions, puis le scénario est PATCH en
versions existantes sont ajoutées

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +_Erreur 404_ : l'id de version n'a pas été trouvé en base de donnée.<br>
pas été trouvée

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +_Erreur 409_ : le status de l'une des versions à mettre à jour est **DRAFT**, mais il est **CURRENT** en base de donnée. La mise à jour n'est pas autorisé.<br>
n'est pas autorisée

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +Pour faire la mise à jour, le service extrait de la base de donnée toutes les versions qui ne sont pas à mettre à jour. Puis recopie les dates de créations de toutes les versions existantes en base d
les versions existantes en base de donnée et replace -> **remplace**

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +Lors de l'appel au DAO, un contrôle est réalisé pour s'assurer que le scénario et chaque version disposent d'un id valide.<br>
chaque version **dispose**

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +Si le scénario n'existe pas en base de donnée, il est considéré comme n'ayant déjà été supprimé, aucune erreure n'est levée.<br>
comme n'ayant **pas** déjà été supprimé

2022-09-13 10:31 UTC, djowalker commented on bot/admin/server/doc/README.md
> +Si le scénario n'existe pas en base de donnée, il est considéré comme n'ayant déjà été supprimé, aucune erreure n'est levée.<br>
aucune erreure -> aucune erreur ->

2022-09-13 13:31 UTC, djowalker approved these changes

2022-09-13 13:35 UTC, merged